### ISSUE TITLE
com.github.housepower:clickhouse-native-jdbc:1.6-stable 插入数据比实际数量大

### ISSUE THREAD

**Issue by yanchaoguo** [housepower/ClickHouse-Native-JDBC#101]
com.github.housepower:clickhouse-native-jdbc:1.6-stable版本 当插入数据超过一个batch规定大小时，会导致最终结果数据量偏大

**Comment by wsg96321** [comment]
I think it is the same as the issue 
[https://github.com/housepower/ClickHouse-Native-JDBC/issues/84#event-2396784309](url)

**Comment by sundy-li** [comment]
#84
