### ISSUE TITLE
Can url be this "jdbc:clickhouse://127.0.0.1:9000?characterEncoding=UTF-8" ？i.e. Specify the Charset to encode

### ISSUE THREAD

**Issue by wozipa** [housepower/ClickHouse-Native-JDBC#107]

**Comment by sundy-li** [comment]
No. But this may be a feature, but now the default charset is UTF-8.

**Comment by wozipa** [comment]
> No. But this may be a feature, but now the default charset is UTF-8.

Ok, Thank you!

**Comment by uschindler** [comment]
@sundy-li: Sorry, the default charset is *not* UTF-8 in the driver. You can see this easily in BinarySerializer, same for FixedString: When it reads a string from the wire protocol, it uses `new String(byte[])` which uses the default charset of the platform and that's not necessarily UTF-8. All this code parts that convert between Bytes and Java Strings MUST use a  `StandardCharsets.UTF_8` parameter to correctly implement your statement! This issue causes to get strings completely broken if the local default charset is not UTF-8 (e.g., on Windows). So the code need a complete cleanup of byte to string conversion!

Please use forbiddenapis Maven/Gradle plugin to catch those horrible bugs! https://github.com/policeman-tools/forbidden-apis

I am currently investigating which JDBC driver to use and will likely provide a Pull Request, as the current code is unuseable in internationalized platforms.

**Comment by uschindler** [comment]
I created a Pull Request #132 to fix th issues with platform default character sets and also wrong decimal symbols in asian languages (like Hindu countries when formatting dates).

To allow to make charset configureable, we should just change `StandardCharsets.UTF_8` in the source code by the URL-configurable character set. This would be a followup PR.

Thanks,
Uwe

**Comment by pan3793** [comment]
@wozipa Currently, we are hard code to force use UTF8 . Do you think we can close this issue?

**Comment by uschindler** [comment]
I still think as an improvement, it should be possible to change the encoding for en/decoding to something else than UTF-8. This is important, because internally Clickhouse is flexible and keeps strings just as binary data, so the consumer of the data has to take care.

Of course, I'd recommend to always store Strings as UTF-8...

**Comment by pan3793** [comment]
@uschindler Good point. Let's keep this issue open.
