### ISSUE TITLE
issue batch insert java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by ssky1** [housepower/ClickHouse-Native-JDBC#120]
### JDBC version in pom.xml
ClickHouse server version 20.3.4

### ClickHouse version
2.0-stable

### Error  logs
Caused by: java.nio.BufferOverflowException
        at java.nio.Buffer.nextPutIndex(Buffer.java:521)
        at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:169)
        at com.github.housepower.jdbc.buffer.ByteArrayWriter.writeBinary(ByteArrayWriter.java:26)
        at com.github.housepower.jdbc.serializer.BinarySerializer.writeVarInt(BinarySerializer.java:32)
        at com.github.housepower.jdbc.serializer.BinarySerializer.writeStringBinary(BinarySerializer.java:73)
        at com.github.housepower.jdbc.data.type.DataTypeString.serializeBinary(DataTypeString.java:41)
        at com.github.housepower.jdbc.data.Column.write(Column.java:58)
        at com.github.housepower.jdbc.data.Block.appendRow(Block.java:49)
        at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addParameters(ClickHousePreparedInsertStatement.java:60)
        at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.addBatch(ClickHousePreparedInsertStatement.java:50)
        at test_clickhouse.CLICKHOUSE_TALEND$tJDBCOutput_2_OutputFunction.call(CLICKHOUSE_HIVE.java:868)

## here is the talend generated code that call the driver and insert data 

                 public void call(java.util.Iterator<row1Struct> dataIterator)
				throws java.lang.Exception {
			java.sql.Connection connection = tJDBCConfiguration_1_ConnectionPool
					.get(context).borrowObject();
			try {

				java.sql.PreparedStatement pstmt_tJDBCOutput_2 = connection
						.prepareStatement("INSERT INTO "
								+ "clickhouse_distributed_table"
								+ " (col1,col2,col3,col4,col5,col6) VALUES(?,?,?,?,?,?)");
				while (dataIterator.hasNext()) {
					row1Struct conntJDBCOutput_2_1 = dataIterator.next();
					if (conntJDBCOutput_2_1.col1 == null) {
						pstmt_tJDBCOutput_2.setNull(1, java.sql.Types.VARCHAR);
					} else {
						pstmt_tJDBCOutput_2.setString(1,
								conntJDBCOutput_2_1.col1);
					}

					if (conntJDBCOutput_2_1.col2 == null) {
						pstmt_tJDBCOutput_2.setNull(2, java.sql.Types.VARCHAR);
					} else {
						pstmt_tJDBCOutput_2.setString(2,
								conntJDBCOutput_2_1.col2);
					}

					if (conntJDBCOutput_2_1.col3 == null) {
						pstmt_tJDBCOutput_2.setNull(3, java.sql.Types.VARCHAR);
					} else {
						pstmt_tJDBCOutput_2.setString(3,
								conntJDBCOutput_2_1.col3);
					}

					if (conntJDBCOutput_2_1.col4 == null) {
						pstmt_tJDBCOutput_2.setNull(4, java.sql.Types.VARCHAR);
					} else {
						pstmt_tJDBCOutput_2.setString(4,
								conntJDBCOutput_2_1.col4);
					}

					if (conntJDBCOutput_2_1.col5 == null) {
						pstmt_tJDBCOutput_2.setNull(5, java.sql.Types.VARCHAR);
					} else {
						pstmt_tJDBCOutput_2.setString(5,
								conntJDBCOutput_2_1.col5);
					}

					if (conntJDBCOutput_2_1.col6 == null) {
						pstmt_tJDBCOutput_2.setNull(6, java.sql.Types.VARCHAR);
					} else {
						pstmt_tJDBCOutput_2.setString(6,
								conntJDBCOutput_2_1.col6);
					}

					pstmt_tJDBCOutput_2.addBatch();
					batchSizeCounter++;
					if (batchSizeCounter >= batchSize) {
						try {
							pstmt_tJDBCOutput_2.executeBatch();
						} catch (Exception e) {
							throw (e);
						}
						pstmt_tJDBCOutput_2.clearBatch();
						batchSizeCounter = 0;
					}

				} // end while (dataIterator.hasNext())

				if (batchSizeCounter != 0) {
					try {
						pstmt_tJDBCOutput_2.executeBatch();
					} catch (Exception e) {
						throw (e);
					}
					pstmt_tJDBCOutput_2.clearBatch();
				}

				pstmt_tJDBCOutput_2.close();

			} finally {
				if (connection != null) {
					tJDBCConfiguration_1_ConnectionPool.get(context)
							.returnObject(connection);
				}
			}
		}

### Steps to reproduce

Hi,

I am trying to insert  200K rows in a click house distributed table from a talend job (tJdbcOutput component) using ClickHouse-Native-JDBC driver 

above is the code generated by talend to insert in clickhouse table using the driver  

the batch size in talend is set to 1000  (batchSize = 1000)

when I select only 100 rows in input, I don't get this error 

but when I select the whole table (200k) in input , I get the error although in the java code 
clearBatch is called after each 1000 rows being committed !

So I am suspecting that buffer isn't being cleared  ?!

thanks

**Comment by sundy-li** [comment]
Sorry for this bug, and it's fixed in #116
