### ISSUE TITLE
SettingKey.connect_timeout - seconds - by use in Socket as milliseconds

### ISSUE THREAD

**Issue by gapikru** [housepower/ClickHouse-Native-JDBC#131]
### JDBC version in pom.xml
2.1
### Other descriptions
PhysicalConnection.openPhysicalConnection()

socket.connect(endpoint, configure.connectTimeout()); 

In documentation

https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#connect(java.net.SocketAddress,%20int)

timeout - the timeout value to be used in milliseconds.

FIX:

ClickHouseConfig(String url, Properties properties) {
...
    this.connectTimeout = (obj = settings.remove(SettingKey.connect_timeout)) == null ? 0 : (Integer) obj * 1000;
...
}

**Comment by sundy-li** [comment]
#91
