### ISSUE TITLE
Complex expressions in INSERT VALUES?

### ISSUE THREAD

**Issue by bgranvea** [housepower/ClickHouse-Native-JDBC#149]
it is more a question than an issue.

README lists in restrictions: "Complex values expression, Like INSERT INTO test_table VALUES(toDate(123456))". This is potential blocker for us to move from Clickhouse-jdbc to Clickhouse-native-jdbc. 

So my question is: is this a limitation in the native protocol and thus will never be implemented? how does it work in clickhouse-client?

thanks.

**Comment by sundy-li** [comment]
Yes, it's hard to support this feature in batch insert mode. 
Maybe it's ok to use default/alias column in ClickHouse, such as

```
its UInt64,
time DateTime default toDateTime(its/ 1000),
day default toDate(time)
```

**Comment by pan3793** [comment]
>  Is this a limitation in the native protocol? 

Not TCP(native) protocol, but the insert mode. Currently, we only implement the batch insert mode.

> How does it work in clickhouse-client?

Basically, the process is:

1. parse the `INSERT` SQL 
2. extract type and values of each column
3. assemble the values by column, then encode and compress the data into block
4. send blocks to ClickHouse server

So, unless we implement a calculate engine same as ClickHouse Server, we can't handle the INSERT statement which contains expressions.

> Thus will never be implemented?

Not exactly.

There is another insert mode support by ClickHouse TCP(native) protocol, just send SQL text as is, and ClickHouse Server will handle the rest things. We implement the `QUERY` SQL in this mode.

@sundy-li Correct me if anything I said wrong.

Currently, we have no plan to implement it, but PR is welcome.
