### ISSUE TITLE
Project structure improvement suggestion

### ISSUE THREAD

**Issue by pan3793** [housepower/ClickHouse-Native-JDBC#156]
## What changes were proposed in this suggestion?

Split the project to 3 modules:

- clickhouse-native-jdbc
- clickhosue-native-jdbc-shaded
- example

## Backgrounds

Since Hadoop & Spark bundled lz4 and joda jars, it's a risk to encounter the version conflicts, a shaded version with no extra dependencies would be a ideal solution.

Actually the project has provided shaded package with relocated dependencies now, but when we search in https://mvnrepository.com/, we can't find it directly.
Further, even we found it in [view all](https://repo1.maven.org/maven2/com/github/housepower/clickhouse-native-jdbc/2.2-stable/), and include it in `pom.xml` with below code, the transitive dependencies are also included, we need exclude them explicitly.
```
<dependency>
    <groupId>com.github.housepower</groupId>
    <artifactId>clickhouse-native-jdbc</artifactId>
    <version>2.2-stable</version>
    <classifier>shaded</classifier>
</dependency>
```

## Benefits

If we split it to 3 modules, and provide the normal version via `clickhosue-native-jdbc` module (as is), provide the shaded&relocated version via `clickhosue-native-jdbc-shaded` module, which artifactId is `clickhosue-native-jdbc-shaded` and without classifier and transitive dependencies, then we can search it in https://mvnrepository.com/ and get a *clean* `clickhosue-native-jdbc` driver.
Finally, just move the classes in package `example` to `example` module.

BTW, since Java 8 introduced `java.time` API, can we drop joda?

**Comment by sundy-li** [comment]
Thanks, it makes sense.
-  Split `clickhosue-native-jdbc-shaded` and `clickhosue-native-jdbc`
-  Example module is not necessary, it's only for examples.
-  `joda` suggest us to migrate to `java.time`, so it'll be better.

 could you help make a pr improve it?

**Comment by pan3793** [comment]
Thanks for your confirm, I'm working on it.
