### ISSUE TITLE
Better identification of `INSERT`

### ISSUE THREAD

**Issue by zhang2014** [housepower/ClickHouse-Native-JDBC#16]
> What about: select * from test where name = 'VALUES (a,b,c,d)' ?
It's not an insert query, but matches the Pattern, should use QuotedLexer to check it's an insert query.

reference: https://github.com/houseflys/ClickHouse-Native-JDBC/pull/14/commits/cf51d656603332952ab105f0d6610960ceb8b782

**Comment by zhang2014** [comment]
after #19

**Comment by sundy-li** [comment]
fixed in `ClickHouseStatement.executeUpdate()`
