### ISSUE TITLE
Question: clickhouse-jdbc comparison?

### ISSUE THREAD

**Issue by otisg** [housepower/ClickHouse-Native-JDBC#18]
Hi.  How is this different from https://github.com/yandex/clickhouse-jdbc ?

**Comment by sundy-li** [comment]
` https://github.com/yandex/clickhouse-jdbc ` is based on HTTP protocol, surly `Native JDBC` could be much faster than that.

**Comment by zhang2014** [comment]
Benchmark will be available after #19

**Comment by sundy-li** [comment]
#108
