### ISSUE TITLE
Date type  data insert clickhouse is not correct

### ISSUE THREAD

**Issue by maimaip** [housepower/ClickHouse-Native-JDBC#192]
### JDBC version in pom.xml

com.github.housepower:clickhouse-native-jdbc:2.3-stable
### ClickHouse version
20.10.1

### Error  logs
spark clomn is string
i use spark  to_date() transfer date and insert clickhouse  
clickhouse is date

### Steps to reproduce
i use spark  syn data from hive to clikhouse ;
i find hive  date is  2020-11-05
but i use spark syn clickhouse  then date is 2020-11-04
spark version 3.0
### Other descriptions

![image](https://user-images.githubusercontent.com/28518838/98346151-88d40180-2050-11eb-9591-f31af1c3e0b6.png)

![image](https://user-images.githubusercontent.com/28518838/98347508-70fd7d00-2052-11eb-96e1-eabe87d79fdf.png)

**Comment by maimaip** [comment]
i use com.github.housepower:clickhouse-native-jdbc:1.7-stable is correct

**Comment by pan3793** [comment]
@maimaip By default, we use server timezone, try append jdbc parameter `use_client_time_zone=true` on url switch to client timezone.

**Comment by pan3793** [comment]
@maimaip I find it does has issue on mainline as your description, investigating on it.

**Comment by maimaip** [comment]
@sundy-li thanks

**Comment by pan3793** [comment]
@maimaip We just release 2.4.0, this bug should be fixed, please have try.
