### ISSUE TITLE
can  support clickhouse  multiple instances of cluster ？

### ISSUE THREAD

**Issue by lingya** [housepower/ClickHouse-Native-JDBC#193]
### JDBC version in pom.xml
0.2.4
### ClickHouse version

20.8

**Comment by lingya** [comment]
can support clickhouse multiple instances of cluster ？

**Comment by pan3793** [comment]
Not yet. And 0.2.4 should be `yandex/clickhouse-jdbc` version. Our latest version is 2.3-stable.

**Comment by pan3793** [comment]
close because of duplicate with #93
