### ISSUE TITLE
DateTime64/DateTime64(3)/DateTime64(6) 处理不正确，只能用 DateTime64(9)

### ISSUE THREAD

**Issue by gmxyb** [housepower/ClickHouse-Native-JDBC#210]
jdbc 驱动代码中，貌似没有仔细区分，都当作 DateTime64(9) 来处理了

**Comment by pan3793** [comment]
Thanks for your report. It's definitely a bug, currently all `DataTime64` hardcode with nanosecond.

**Comment by pan3793** [comment]
Have a check on ClickHouse document, the description of `Datetime64` scale is not very clear.
From source code, got `DateTime64` default_scale_=3, min_scale=0, max_scale=9

**Comment by gmxyb** [comment]
In DataTypeDateTime64 : 
```
    public Object deserializeTextQuoted(SQLLexer lexer) throws SQLException {
        //StringView dataTypeName = lexer.bareWord();
        //Validate.isTrue(dataTypeName.checkEquals("toDateTime64"));
        //Validate.isTrue(lexer.character() == '(');
        Validate.isTrue(lexer.character() == '\'');
        int year = lexer.numberLiteral().intValue();
        Validate.isTrue(lexer.character() == '-');
        int month = lexer.numberLiteral().intValue();
        Validate.isTrue(lexer.character() == '-');
        int day = lexer.numberLiteral().intValue();
        Validate.isTrue(lexer.isWhitespace());
        int hours = lexer.numberLiteral().intValue();
        Validate.isTrue(lexer.character() == ':');
        int minutes = lexer.numberLiteral().intValue();
        Validate.isTrue(lexer.character() == ':');
        int seconds = lexer.intLiteral();
        
        int nanos = 0;
        if(lexer.character() == '.') {
          nanos = lexer.intLiteral();
          String str = String.valueOf(nanos);
          nanos = Integer.parseInt((str + "000000000").substring(0, 9));
        }
        Validate.isTrue(lexer.character() == '\'');

        ZonedDateTime zdt = ZonedDateTime.of(year, month, day, hours, minutes, seconds, nanos, tz);
        return Timestamp.from(zdt.toInstant());
    }

```

**Comment by pan3793** [comment]
@gmxyb Good catch. Would you like to send PR to fix this issue?

**Comment by pan3793** [comment]
@gmxyb As we already have `lexer.numberLiteral()`, what do you think if we parse a double then split it to seconds and nanos?

**Comment by gmxyb** [comment]
> @gmxyb As we already have `lexer.numberLiteral()`, what do you think if we parse a double then split it to seconds and nanos?

seconds and nanos NOT decimal number,  The maximum value of seconds is 59, not 99

**Comment by pan3793** [comment]
> seconds to nanos NOT decimal

That's right, but what will cause if we parse it to a double?
For example, when parse `2020-01-01 12:34:56.7892`, will get `56.7892`, then `seconds=56`, `nanos=789_200_000`.

> `nanos = lexer.intLiteral();` `nanos = Integer.parseInt((str + "000000000").substring(0, 9));`

Follow your code, when parse `2020-01-01 12:34:56.001`, will get `nanos=100_000_000`, how can we handle this?

**Comment by gmxyb** [comment]
Yes, u r right. @pan3793
