### ISSUE TITLE
When I use Decimal(36,16),JDBC reports exception  "precision[38] is out of boundary"

### ISSUE THREAD

**Issue by wallace-clickhouse** [housepower/ClickHouse-Native-JDBC#229]
When I use Decimal(36,16) in my SQL to query,JDBC reports exception "precision[38] is out of boundary".With the same SQL,if I use clickhouse-client,it runs well,So is it a bug?Thanks!

**Comment by pan3793** [comment]
Currently only implement Decimal32 and Decimal64, IOW, only support precision between 0 and 18.
