### ISSUE TITLE
Recommended compatible "java.sql.Date" and "java.sql.Timestamp"  in DataTypeDate.java

### ISSUE THREAD

**Issue by gmxyb** [housepower/ClickHouse-Native-JDBC#230]
@Override
    public void serializeBinary(Object data, BinarySerializer serializer) throws SQLException, IOException {
        // begin add ----------------------- 
        if(data instanceof java.sql.Timestamp) {
          long epochDay = ((java.sql.Timestamp) data).toLocalDateTime().toLocalDate().toEpochDay();
          serializer.writeShort((short) epochDay);
          return;
        }
        // end add ----------------------- 
        long epochDay = ((Date) data).toLocalDate().toEpochDay();
        serializer.writeShort((short) epochDay);
    }

**Comment by pan3793** [comment]
`java.sql.Date` is designed mapping SQL `Date` and `java.sql.Timestamp` mapping SQL `DateTime`, I don't think it's a good idea to mix them.
