### ISSUE TITLE
What version I can use for BalancedClickhouseDataSource

### ISSUE THREAD

**Issue by shubham721** [housepower/ClickHouse-Native-JDBC#232]
Hi guys,
Are you planning to release the version soon?
In 2.4.2, I can't see some classes like ClickhouseDriver, BalancedClickhouseDataSource
to use connection pooling like Hikari.

**Comment by pan3793** [comment]
`BalancedClickhouseDataSource` is available on master branch code with version v2.5.0-SNAPSHOT, but v2.5.0 is not prepared to release. You can follow the dev doc to build in local or publish to private nexus to have a try.
https://housepower.github.io/ClickHouse-Native-JDBC/dev/internal_release.html

**Comment by pan3793** [comment]
> Are you planning to release the version soon?
v2.5.0 is not yet ready. Currently, we plan to release it in a few weeks.
