### ISSUE TITLE
clickhouse-go compatible DSN

### ISSUE THREAD

**Issue by yuzhichang** [housepower/ClickHouse-Native-JDBC#234]
[clickhouse-go DSN](https://github.com/ClickHouse/clickhouse-go#dsn):
- alt_hosts - comma separated list of single address host for load-balancing
- connection_open_strategy - random/in_order (default random).

These parameters enables load-balance and fault- toleration.

**Comment by pan3793** [comment]
I'm not familiar with Golang database access interface, on Java side, the JDBC interface provids `Driver` and `DataSource` as standard interfaces to access database. 
As current implementation, `ClickHouseDriver` support to connect single node, and `BalancedClickHouseDataSource` support to connect multi nodes. The equivalent of `alt_hosts` is placed in jdbc url, i.e. `jdbc:clickhouse://localhost:1234,another.host.com:4321/ppc`, `connection_open_strategy` is hardcode as `random`.

Conclusively, I'd like to add a config like `connection_open_strategy` in the future, but will not provide `alt_hosts `

**Comment by yuzhichang** [comment]
Fair enough.
And what about `block_size`?

**Comment by pan3793** [comment]
Currently, we can't control block size directly, it controlled by batch size mediately.

The typical batch insert is:
```
String insertStmt = "insert into t (?, ?)";
PrepareStatement stmt = conn.prepareStatement(insertStmt);
int rowCount = 0;
for (var record: records) {
  stmt.set(1, record.getX());
  stmt.set(2, record.getY());
  if(rowCount++ > batchSize)
    stmt.executeBatch();
    rowCount = 0;
}
stmt.executeBatch()
```
Every `executeBatch()` is assembled as a block.

If we want to directly and accurately control the block size, firstly we need to measure data size, and then implement a strategy to spill block properly. Maybe will implement it in future, but not in high priority.

**Comment by sundy-li** [comment]
>  block_size - maximum rows in block (default is 1000000). If the rows are larger then the data will be split into several blocks to send them to the server. If one block was sent to the server, the data will be persisted on the server disk, we can't rollback the transaction. So always keep in mind that the batch size no larger than the block_size if you want atomic batch insert.

**Comment by sundy-li** [comment]
we have BalanceDataSource support now in https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/BalancedClickhouseDataSource.java
