### ISSUE TITLE
How to set JDBC connection string for Clickhouse cluster 

### ISSUE THREAD

**Issue by hyy613** [housepower/ClickHouse-Native-JDBC#244]
i set up clickhouse cluster with 3 node . but when i use jdbc connection connection ,i can only choose one of the ip to generate connection string jdbc:clickhouse://${ip}:9000/${database}?user=***&password=*** .  seems not find related API to connect to cluster string .
i have to implements the code that setup 3 connection with 3 diffierent connection string and when insert data i would random select one connection . 

### Error logs

```
paste your error logs here
```

**Comment by sundy-li** [comment]
There are `BalancedClickhouseDataSource `  support in https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/BalancedClickhouseDataSource.java

**Comment by sundy-li** [comment]
I will update the docs in usage.
