### ISSUE TITLE
Connection frozen when using 2 queries in a single try-with-resources

### ISSUE THREAD

**Issue by sbouchex** [housepower/ClickHouse-Native-JDBC#254]
### Environment

- OS version: Windows
- JDK version: 8
- ClickHouse Server version: 20.11.5.18
- ClickHouse Native JDBC version: 2.4.3
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

While executing this piece of code, the connection is frozen when reading the second results set :

Create a JDBC connection (with standard parameters), then execute the following code :

**Sample :**
```
try (Statement s = c.createStatement();
ResultSet rs1 = s.executeQuery("SELECT name,engine FROM system.tables");
ResultSet rs2 = s.executeQuery("SELECT name,engine FROM system.tables")) {
     while (rs1.next()) {
          String tableName = rs1.getString("name");
          String engine = rs1.getString("engine");
     }
     while (rs2.next()) {
          String tableName = rs2.getString("name");
          String engine = rs2.getString("engine");
     }
}
```
The thread is frozen while doing "while (rs2.next())"

**Stack:**
```
SocketInputStream.socketRead0(FileDescriptor, byte[], int, int, int) line: not available [native method]	
SocketInputStream.socketRead(FileDescriptor, byte[], int, int, int) line: 116	
SocketInputStream.read(byte[], int, int, int) line: 171	
SocketInputStream.read(byte[], int, int) line: 141	
SocketBuffedReader.refill() line: 80	
SocketBuffedReader.readBinary() line: 48	
BinaryDeserializer.readVarInt() line: 38	
RequestOrResponse.readFrom(BinaryDeserializer, PhysicalInfo$ServerInfo) line: 46	
PhysicalConnection.receiveResponse(int, PhysicalInfo$ServerInfo) line: 99	
ClickHouseConnection.lambda$sendQueryRequest$0(PhysicalConnection) line: 162	
1609742538.get() line: not available	
QueryResponse.consumeDataResponse() line: 53	
QueryResponse.access$100(QueryResponse) line: 24	
QueryResponse$1.fill() line: 70	
QueryResponse$1.hasNext() line: 85	
ClickHouseResultSet.fetchBlock() line: 341	
ClickHouseResultSet.next() line: 332	
Schema.load(Connection, String) line: 43	
```
If I use 2 try-with-resources instead, it's working fine.

**Comment by sundy-li** [comment]
That's expected,  JDBC is not for parallelism queries, you must use different Statements for different queries.

**Comment by sbouchex** [comment]
@pan3793 I'm sorry but the issue occurs also when using 2 different statements from the same connection :
 1. Connection is open
 2. "ST1": First statement doing a select query (a full scan on various elements)
 3. While iterating on ST1, create a new statement "ST2" to query the same table
 4. Connection is frozen while reading results from the "ST1"

The problem seems to be related to the fact that the driver do not handle 2 simultaneous statements on the same connexions.

This kind of behaviours comes from Apache OJB and it's difficult to modify it.

Sample:
public static void main(String[] args) throws Exception {
        Connection connection = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9000/db?user=my_user&password=my_password");
        Statement stmt = connection.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT * from codes A0");
        	long nb = 0;
            while (rs.next()) {
            	Statement stmt2 = connection.createStatement();
	    		ResultSet rs2 = stmt2.executeQuery("SELECT * FROM codes A0 where A0.id=1");
	    		while (rs2.next()) {
	          	System.out.println(nb+ " -> " + rs2.getString(1) + "\t" + rs2.getLong(2));
	    		}
	    		rs2.close();
	    		stmt2.close();
            }
            System.out.println(rs.getString(1) + "\t" + rs.getLong(2));
            nb++;
            System.out.println(nb);
    }

**Comment by pan3793** [comment]
@sbouchex Thanks for report this issue with clear informations. But, unfortunately, the current implementation can't handle your scenario.
In short, we implement one jdbc connection mapping one tcp connection, and clickhouse tcp protocol must process queries in sequences.
