### ISSUE TITLE
getBool is not working on a UInt8 column

### ISSUE THREAD

**Issue by sbouchex** [housepower/ClickHouse-Native-JDBC#255]
Environment
OS version: Windows
JDK version: 8
ClickHouse Server version: 20.11.5.18
ClickHouse Native JDBC version: 2.4.3
(Optional) Spark version: N/A
(Optional) Other components' version: N/A

### Error logs

```
java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Boolean
```

### Steps to reproduce

Create a table with a UInt8 column and do a getBool on the column

### Other descriptions

In DataTypeInt8.deserializeBinary, the value is returned a short but in ClickHouseResultSet.getBoolean, the value is casted from short to boolean which is NOT POSSIBLE.

**Comment by pan3793** [comment]
closed by #256
