### ISSUE TITLE
Handle Nothing datatype

### ISSUE THREAD

**Issue by sbouchex** [housepower/ClickHouse-Native-JDBC#260]
Environment
OS version: Windows
JDK version: 8
ClickHouse Server version: 20.11.5.18
ClickHouse Native JDBC version: 2.4.3
(Optional) Spark version: N/A
(Optional) Other components' version: N/A

### Error logs

```
Unknown data type: Nothing
```

### Steps to reproduce

Create a query that return a empty Array

### Other descriptions

See [https://clickhouse.tech/docs/en/sql-reference/data-types/special-data-types/nothing/](https://clickhouse.tech/docs/en/sql-reference/data-types/special-data-types/nothing/)

**Comment by pan3793** [comment]
@sbouchex Thanks for contribution! And just one tip. If you comment in PR with _close #260_ or _fix #260_ and the referred issue will be auto closed once the PR is merged!
