### ISSUE TITLE
ClickHouseResultSet.getTimestamp(col, calendar) implementation proposal

### ISSUE THREAD

**Issue by sbouchex** [housepower/ClickHouse-Native-JDBC#265]
### Environment

- OS version: Windows
- JDK version: 8
- ClickHouse Server version: 20.11.5.18
- ClickHouse Native JDBC version: 2.4.3
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Other descriptions
`ClickHouseResultSet.getTimestamp(name, calendar)` & `ClickHouseResultSet.getTimestamp(index, calendar)` are not implemented but the current implementation of `DataTypeDateTime` prevents us from doing it as the initial time zone (coming from the server or defined by the user in the connection properties) is unknown once in `ClickHouseResultSet.getTimestamp` (as we only manipulate `Timestamp` object) 

The only solution would be to modify `DataTypeDateTime` to return something different from `Timestamp` but something that includes the source timezone.

In:

- `ClickHouseResultSet.getTimestamp(name)` : No special processing has to be done
- `ClickHouseResultSet.getTimestamp(index)` : No special processing has to be done
- `ClickHouseResultSet.getTimestamp(name, calendar)` : Data tz is present and give the ability to change it per to user request
- `ClickHouseResultSet.getTimestamp(index, calendar)` : Data tz is present and give the ability to change it per to user request

Sound ok for you ?

**Comment by pan3793** [comment]
Thanks for this proposal.

> The only solution would be to modify DataTypeDateTime to return something different from Timestamp but something that includes the source timezone.

I agree with you. 

Furthermore, we have a plan to refactor and decouple the types between `IDataType` and JDBC interfaces (setters in `ClickHousePreparedStatement` and getters in `ClickHouseResultSet`), then a type converter layer is needed to convert types between each other. 

This would be a big refactor, and I think it okay to only change the return type of `DataTypeDateTime` to something like `ZonedDateTime` or `OffsetDateTime` for now. The only thing I want to remind is please use `java.time` API instead of legacy `Date` API.

**Comment by pan3793** [comment]
There is a relative PR in yandex/clickhouse-jdbc repo, hope it can be of some help.
https://github.com/ClickHouse/clickhouse-jdbc/pull/418

**Comment by pan3793** [comment]
@sbouchex Merry Christmas and wanna know are you start to work on this issue? I'm planning to release v2.5.0 in fews days, please let me know if you want the release include this issue?

**Comment by sbouchex** [comment]
@pan3793 I have started working on it but i will continue end of next week, and I'm not sure it will be finished for the upcoming release.

**Comment by pan3793** [comment]
@sbouchex Got it. Consider we have introduced lots of features since v2.4.0, I will start the v2.5.0 release in tomorrow if all things look good. 
Let's move this issue to the next release, at meantime, I'm will work on #247, and will add more details later.

**Comment by pan3793** [comment]
move to #288

**Comment by pan3793** [comment]
close by #288
