### ISSUE TITLE
Rewrite StringView implements CharSequence

### ISSUE THREAD

**Issue by pan3793** [housepower/ClickHouse-Native-JDBC#269]
Pave the way for #247

Currently, `DataTypeString` accepts three types in `#serializeBinary`, which are `String`, `StringView` and `byte[]`.
To add Generic Type constraint on `DataTypeString`, we need to unified the types into one common super type, I proposal to refactor `StringView` implements `CharSequence` and introduce `BytesCharSeq` also implements `CharSequence` to be a wrapper of `byte[]`, after this change, `DataTypeString` can be `DataTypeString<CharSequence>`.

Because `IDataType` couple with JDBC interface type now, the phase 1 only change `StringView`.

**Comment by sundy-li** [comment]
Good point,  I agree with that.
