### ISSUE TITLE
spark write into clickhouse

### ISSUE THREAD

**Issue by ningyanhui** [housepower/ClickHouse-Native-JDBC#273]
### Environment

- OS version: Red Hat 4.8.5-16
- JDK version: 8
- ClickHouse Server version: 20.8.3.18
- ClickHouse Native JDBC version: 2.4
- (Optional) Spark version: N/A 2.4
- (Optional) Other components' version: N/A

### Error logs
Caused by: java.lang.Throwable: Code: 202, e.displayText() = DB::Exception: Too many simultaneous queries. Maximum: 16
```
paste your error logs here
```

### Steps to reproduce
config

<background_schedule_pool_size>80</background_schedule_pool_size>
<background_pool_size>80</background_pool_size>
<max_final_threads>80</max_final_threads>
<background_buffer_flush_schedule_pool_size>80</background_buffer_flush_schedule_pool_size>
<background_distributed_schedule_pool_size>80</background_distributed_schedule_pool_size>

<max_memory_usage>64000000000</max_memory_usage>
<max_insert_threads>80</max_insert_threads>

### Other descriptions
I want to known the '16' belong to ?

**Comment by sundy-li** [comment]
Try to increase your settings `max_concurrent_queries`

**Comment by ningyanhui** [comment]
> max_concurrent_

**Comment by ningyanhui** [comment]
> Try to increase your settings `max_concurrent_queries`

the max_concurrent_queries =  100,but this is 16
