### ISSUE TITLE
ClickHouseResultSetMetaData.isSigned is wrong

### ISSUE THREAD

**Issue by baibaichen** [housepower/ClickHouse-Native-JDBC#280]
I believe  [`ClickHouseResultSetMetaData.isSigned`](https://github.com/housepower/ClickHouse-Native-JDBC/blob/99f221532501b1dfe30d91fb21b6ca4e65c949eb/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java#L99) is wrong

```JAVA
    public boolean isSigned(int index) throws SQLException {
        return header.getColumnByPosition(index - 1).name().startsWith("U");
    }
```
we should fix it as 

```java
    public boolean isSigned(int index) throws SQLException {
        return !header.getColumnByPosition(index - 1).type().name().startsWith("U");
    }
```

**Comment by sundy-li** [comment]
You are right. We do not have any test cases for `ClickHouseResultSetMetaData`
