### ISSUE TITLE
Spark load table Setting numPartitions does not take effect

### ISSUE THREAD

**Issue by ClownfishYang** [housepower/ClickHouse-Native-JDBC#298]
### Environment

- Centos 7: 
- JDK 1.8:
- ClickHouse Server version: 20.2.1.2183
- ClickHouse Native JDBC version: 2.5.0
- (Optional) Spark version: 2.3.2

Because I need to read a very large table, but from the log I find that the query is always WHERE 1=0, which affects my processing performance very much.
Setting numPartitions does not take effect. There is still only one task to read the table.
```
def main(args: Array[String]): Unit = {
    // registerDialect
    JdbcDialects.registerDialect(ClickHouseDialect)

    // spark config
    var sparkConf = new SparkConf()
    val sparkSession = SparkSession.builder().config(sparkConf)
      .master("local")
      .appName("xxx").getOrCreate()

    // read table option
    val ch_options = Map(
      "driver" -> "com.github.housepower.jdbc.ClickHouseDriver",
      "url" -> "jdbc:clickhouse://xxxx:9000",
      "user" -> "default",
      "password" -> ""
    )

    // read table
    val paramData: DataFrame = sparkSession.read
      .format("jdbc")
      .options(ch_options)
      .option("fetchsize", batchSize)
      .option("numPartitions", numPartitions)
      .option("dbtable", sourceTable)
      .load
    paramData.show()
}
```

**Comment by ClownfishYang** [comment]
I need to solve this problem as soon as possible. Please help me. Thank you very much.

**Comment by sundy-li** [comment]
Hello, why you want multi task to read the table? 

It's just one SQL to fetch data from ClickHouse.

**Comment by pan3793** [comment]
It's the limitation of `JDBCRDD`, we can't do anything here.
An approach is spilt your query SQL into N and union them into one `DataFrame`.

**Comment by ClownfishYang** [comment]
> Hello, why you want multi task to read the table?
> 
> It's just one SQL to fetch data from ClickHouse.
Yes, I understand what you are saying, but some computations need to load all the data, and using only one task to read is very slow, I think it should be able to do partition reads like Hive or HBase.

**Comment by ClownfishYang** [comment]
> An approach is spilt your query SQL into N and build a jdbc `DataSource` on each one, then union them into one `DataFrame`.
> 
> And have you tried using `numPartitions` with the following parameters?
> 
> ```
> val columnName = "colName"
> val lowerBound = 1,
> val upperBound = 10000000,
> val numPartitions = 10,
> ```
> 
> From Spark codebase:
> 
> ```scala
> // the column used to partition
> val partitionColumn = parameters.get(JDBC_PARTITION_COLUMN)
> // the lower bound of partition column
> val lowerBound = parameters.get(JDBC_LOWER_BOUND)
> // the upper bound of the partition column
> val upperBound = parameters.get(JDBC_UPPER_BOUND)
> // numPartitions is also used for data source writing
> require((partitionColumn.isEmpty && lowerBound.isEmpty && upperBound.isEmpty) ||
>   (partitionColumn.isDefined && lowerBound.isDefined && upperBound.isDefined &&
>     numPartitions.isDefined),
>   s"When reading JDBC data sources, users need to specify all or none for the following " +
>     s"options: '$JDBC_PARTITION_COLUMN', '$JDBC_LOWER_BOUND', '$JDBC_UPPER_BOUND', " +
>     s"and '$JDBC_NUM_PARTITIONS'")
> ```

Yes, this is an example of a concurrent read on Spark's official website, which is why I'm confused, because it doesn't work. I can see from the log that it only performs a `SELECT * FORM TABLE WHERE 1=0` statement.

```
// 1
val paramData: DataFrame = sparkSession.read
        .jdbc()
      .format("jdbc")
      .options(ch_options)
      .option("fetchsize", 10000)
      .option("partitionColumn","rownum")
      .option("numPartitions", 10)
      .option("lowerBound", 0)
      .option("upperBound", 10000000)
      .option("dbtable", "view_test")
      .load()
paramData.show()
// 2
val properties = new Properties()
    sparkSession.read.jdbc("jdbc:clickhouse://xxx:9000",
      "view_test",
      "rownum",
      0,10000000,
      10,properties
    ).show()
```

Also, I found that the official website supports custom SQL for the table, but it doesn't support it here either.

**Comment by pan3793** [comment]
> Also, I found that the official website supports custom SQL for the table, but it doesn't support it here either.

Basically, it's only a Jdbc Dialect which based on Spark Jdbc DataSource, the features show in Spark docs should work. If it doesn't, please provide reproducible code so we can do some investigation.

**Comment by ClownfishYang** [comment]
> > Also, I found that the official website supports custom SQL for the table, but it doesn't support it here either.
> 
> Basically, it's only a Jdbc Dialect which based on Spark Jdbc DataSource, the features show in Spark docs should work. If it doesn't, please provide reproducible code so we can do some investigation.

After a lot of trial and error, numtionPartitions worked, and I found that the partitionColumn was able to use function, which was great.
This is the way I'm using it now.
```
    val paramData: DataFrame = sparkSession.read
      .format("jdbc")
      .options(ch_options)
      .option("fetchsize", batchSize)
      .option("numPartitions", numPartitions)
      .option("partitionColumn","hiveHash(uuid)%"+numPartitions)
      .option("lowerBound", 0)
      .option("upperBound", numPartitions)
      .option("dbtable", sourceTable)
      .load()
```
