### ISSUE TITLE
Type ‘Nullable(Int64)’ will get signed false in resultset metadata

### ISSUE THREAD

**Issue by liuneng1994** [housepower/ClickHouse-Native-JDBC#304]
### Environment

- OS version: macOS Big Sur 11.0.1
- JDK version: oracle jdk 1.8.0_231
- ClickHouse Server version: 20.8.2.3
- ClickHouse Native JDBC version: 2.5.2
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
paste your error logs here
```

### Steps to reproduce
query a Nullable(Int64) type column, the column metadata isSigned will be false, but should be true

**Comment by liuneng1994** [comment]
I'm working on this issue

**Comment by pan3793** [comment]
closed by #305
