### ISSUE TITLE
Merge native client into official JDBC driver

### ISSUE THREAD

**Issue by zhicwu** [housepower/ClickHouse-Native-JDBC#308]
Hello @sundy-li & @pan3793, I'm taking over maintenance of `clickhouse-jdbc`. Starting from its `0.4.0` version, I hope we can support multiple protocols(http, native and grpc) in one JDBC driver. I think you guys did great work on implementing a native client, and I doubt I can do better than that. May I merge your code into the official JDBC driver? I plan to start the work after Spring Festival if no concern.

**Comment by pan3793** [comment]
Glad to see that you are interested in this project, and I'm also agree with that we need a client to leverage advantages of each protocol. But consider the significant difference in project structure, I think the merger process is not an easy task. And to be honest, we are planing a major refactor on the project, maybe we need a talk before the next step.

**Comment by zhicwu** [comment]
Thanks guys. Looking forward to the refactored version. Mean time, I'll think about how to abstract protocol in jdbc driver and design an adaptor for native client.
