### ISSUE TITLE
ClickhouseJdbcUrlParser:ignore undefined setting: max_bytes_before_external_group_by=15000000000

### ISSUE THREAD

**Issue by JunjianS** [housepower/ClickHouse-Native-JDBC#311]
<dependency>
			<groupId>com.github.housepower</groupId>
			<artifactId>clickhouse-native-jdbc-shaded</artifactId>
			<version>2.5.3</version>
		</dependency>

when i set url jdbc:clickhouse://172.0.0.1:9000/test?max_memory_usage=300000000000&max_bytes_before_external_group_by=15000000000&distributed_aggregation_memory_efficient=1
the result is ClickhouseJdbcUrlParser:ignore undefined setting: max_bytes_before_external_group_by=15000000000
, then i found there is no max_bytes_before_external_group_by in SettingKey.

**Comment by pan3793** [comment]
You should defined un-predefined `SettingKey` by:
```
SettingKey userDefined = SettingKey.builder()
        .withName("user_defined")
        .withType(SettingType.UTF8)
        .build();
```
See more detail at: https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/test/java/com/github/housepower/settings/ClickHouseConfigTest.java

The native protocol need to know how to serialize setting values so all `SettingKey`s should be defined explicitly.

**Comment by JunjianS** [comment]
> You should defined un-predefined `SettingKey` by:
> 
> ```
> SettingKey userDefined = SettingKey.builder()
>         .withName("user_defined")
>         .withType(SettingType.UTF8)
>         .build();
> ```
> 
> See more detail at: https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/test/java/com/github/housepower/settings/ClickHouseConfigTest.java
> 
> The native protocol need to know how to serialize setting values so all `SettingKey`s should be defined explicitly.

thanks, it means un-predefined can not set in url like key=value ?

**Comment by pan3793** [comment]
> it means un-predefined can not set in url like key=value ?

Yes
