### ISSUE TITLE
Could we support spark 3.0 version scala 2.12

### ISSUE THREAD

**Issue by mullerhai** [housepower/ClickHouse-Native-JDBC#312]
### Environment

- OS version: 
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
paste your error logs here
```

**Comment by pan3793** [comment]
Yes it support spark 3.0 & scala 2.12. 

Try
```
<dependency>
    <groupId>com.github.housepower</groupId>
    <artifactId>clickhouse-integration-spark_2.12</artifactId>
    <version>${clickhouse-native-jdbc.version}</version>
</dependency>
```

**Comment by mullerhai** [comment]
> Yes it support spark 3.0 & scala 2.12.
> 
> Try
> 
> ```
> <dependency>
>     <groupId>com.github.housepower</groupId>
>     <artifactId>clickhouse-integration-spark_2.12</artifactId>
>     <version>${clickhouse-native-jdbc.version}</version>
> </dependency>
> ```

very thanks !!  I have try to use it
