### ISSUE TITLE
Java Spark JdbcDialects.registerDialect Error

### ISSUE THREAD

**Issue by AlienationX** [housepower/ClickHouse-Native-JDBC#320]
### Environment

- OS version: windows7
- JDK version:jdk1.8.0_221
- ClickHouse Server version: 
- ClickHouse Native JDBC version:clickhouse-integration-spark_2.11
- (Optional) Spark version: spark-sql_2.11
- (Optional) Other components' version: N/A

### Error logs
import org.apache.spark.sql.jdbc.JdbcDialects;
import org.apache.spark.sql.jdbc.ClickHouseDialect;

JdbcDialects.registerDialect(ClickHouseDialect);
JdbcDialects.registerDialect(new ClickHouseDialect());

error message::::  must input class org.apache.spark.sql.jdbc.JdbcDialect

I user Java Spark, not Scala.
How to use registerDialect(ClickHouseDialect) ???

```
paste your error logs here
```

### Other descriptions
<dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>2.4.0.cloudera2</version>
        </dependency>
<dependency>
            <groupId>com.github.housepower</groupId>
            <artifactId>clickhouse-integration-spark_2.11</artifactId>
            <version>2.5.4</version>
        </dependency>

**Comment by pan3793** [comment]
```
import org.apache.spark.sql.jdbc.ClickHouseDialect$;
import org.apache.spark.sql.jdbc.JdbcDialects$;

JdbcDialects$.MODULE$.registerDialect(ClickHouseDialect$.MODULE$);
```
See more at https://stackoverflow.com/questions/12284028/how-can-i-use-a-scala-singleton-object-in-java

**Comment by AlienationX** [comment]
It‘s OK，thank.
