### ISSUE TITLE
Where is the insertion performed? Client connects directly node or distributed view?

### ISSUE THREAD

**Issue by wenyangchou** [housepower/ClickHouse-Native-JDBC#327]
### Environment

- OS version: 
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
paste your error logs here
```

**Comment by pan3793** [comment]
Currently we don't support convert *insert distribute table* to *local table*, it may support in future by spark integration module, but we don't have ETA now.

**Comment by wenyangchou** [comment]
您好。spark在执行插入时，是在worker上直接插入到clickhouse的存储节点，还是聚合在driver端执行的插入。目前执行插入不是借助的分布式表。我的理解对吗？

**Comment by wenyangchou** [comment]
您好。我想确认下写入是客户端选择服务器，还是借助分布式表。如果您有答案，可以留下宝贵回复

**Comment by pan3793** [comment]
> spark在执行插入时，是在worker上直接插入到clickhouse的存储节点，还是聚合在driver端执行的插入。

Executors. I think what you mean worker is actually executor.

> 目前执行插入不是借助的分布式表。我的理解对吗？

No. It's simple JDBC driver, if you set target table as a `distribute table`, it just insert into the distribute table.

**Comment by pan3793** [comment]
> 写入是客户端选择服务器

我不理解这句话是什么意思。我猜你可能想表达："如果客户端发现 INSERT INTO 的表是分布式表，将分析其元数据，自动转换为写其所关联的本地表"。如果我理解正确，答案是：“不是”。前面的若干条回复已经解释过了。

**Comment by wenyangchou** [comment]
非常感谢答复
