### ISSUE TITLE
when to support max_partitions_per_insert_block？？

### ISSUE THREAD

**Issue by JasonDung** [housepower/ClickHouse-Native-JDBC#338]
I need to partition by multiple fields and must have the max_partitions_per_insert_block property.
Otherwise, the data will not be inserted

**Comment by pan3793** [comment]
You can following below code to define settings which not pre-defined By `SettingKey` 
https://github.com/housepower/ClickHouse-Native-JDBC/blob/28d65bffeadef76b0504ef65c08d20f31ec881a0/clickhouse-native-jdbc/src/test/java/com/github/housepower/settings/ClickHouseConfigTest.java#L80

Are you using Spark to insert data? If yes, consider repartition your DataFrame to match the clickhouse Table partition before write.
