### ISSUE TITLE
Spark insert CH，Date  will  shift -1 day

### ISSUE THREAD

**Issue by Guanpx** [housepower/ClickHouse-Native-JDBC#343]
### Environment

- OS version: centOS 7
- JDK version: 1.8
- ClickHouse Server version: 
- ClickHouse Native JDBC version: v2.5.4
- (Optional) Spark version: 2.4.0
- (Optional) Other components' version: N/A

### Steps to reproduce
insert data is :
|2021-01|     **2021-01-13**|2021-05-19 08:00:00|2021-05-13|           1|            |2021-05-13 19:21:07|2021-05-13 19:21:46

when use spark insert to CH, that 2021-01-13 change to 2021-01-12 . . . look like this
|2021-01|     **2021-01-12**|2021-05-19 08:00:00|2021-05-12|           1|            |2021-05-13 19:21:07|2021-05-13 19:21:46

the local tz is Asia/Shanghai
the CH tz is Asia/Shanghai

**Comment by pan3793** [comment]
Sounds like you are using Spark to read data from CSV and write into ClickHouse.
The data type `Date` itself should be timezone no-related. So, I guess there are some thing wrong when you reading data into Spark, can you provide the catalyst schema of the data? And print the data use Spark?

**Comment by Guanpx** [comment]
_the 2021-01-13 type is hive Date_

spark df.show 
|2021-01| **2021-01-13**|2021-05-19 08:00:00|2021-05-13| 1| |2021-05-13 19:21:07|2021-05-13 19:21:46

insert to CH
|2021-01| **2021-01-12**|2021-05-19 08:00:00|2021-05-12| 1| |2021-05-13 19:21:07|2021-05-13 19:21:46

**Comment by pan3793** [comment]
I cannot reproduce the reported problem. If you are still stuck with this problem, please provide reproducible code.
