### ISSUE TITLE
Batch insert rate can't match the benchmark result

### ISSUE THREAD

**Issue by TheXs** [housepower/ClickHouse-Native-JDBC#344]
Hi, there. Just set up my native-jdbc-client. And I just found my avg insert rate was about 12000 rows/s (200000 rows in all and 20000 rows/batch, with 59 columns, 600bytes/row, 10 threads, running on a single node, 12 cpu 128G) by using the executeBatch method. Just wondering how could it differ so much with the insert rate, could I get any setting wrong? Below is the runable code. Best regards.

               this.local.set(DataImport.createDataByRows(batch_count));
                Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
                Connection connection = DriverManager.getConnection("jdbc:clickhouse://xxx.xxx.xx.xx:9000");
                PreparedStatement pstmt = connection.prepareStatement(insertSql);
                Iterator<Map<String, Object>> iterator = this.local.get().values().iterator();
                while(iterator.hasNext()) {
                    Map<String, Object> next = iterator.next();
                    dataInitialization(pstmt);
                    for(String key : next.keySet()) {
                        int index = columns.indexOf(key) + 1;
                        pstmt.setObject(index, next.get(key));
                    }
                    pstmt.addBatch();
                }
                pstmt.executeBatch();
                pstmt.close();
                countDownLatch.countDown();

**Comment by pan3793** [comment]
Not sure what happens, we got benchmark report from [benchmark code](https://github.com/housepower/ClickHouse-Native-JDBC/tree/master/clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/benchmark), and please check [GitHub workflow](https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/.github/workflows/benchmark.yml) to get more details.
