### ISSUE TITLE
Very high CPU utilization when using native driver

### ISSUE THREAD

**Issue by akamensky** [housepower/ClickHouse-Native-JDBC#353]
### Environment

- OS version: Centos 7.5
- JDK version: AdoptOpenJDK 11.0.7
- ClickHouse Server version: `21.5.5 revision 54448`
- ClickHouse Native JDBC version: `2.5.6`
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A
- Kafkaconnect version: `Confluent distribution 6.1.1-2.12`
- Postgresql version: `12.3`

### Error logs
N/A

### Steps to reproduce

1. Heavy load topic (125K-200K messages per second) with 50 partitions
2. 3 node kafkaconnect cluster (physical hosts, not VM) with 16 vCPU (8c/16t) each, 128 GB RAM
3. Clickhouse standalone server (RAID10 on SATA3 SSDs)
4. Postgresql standalone server (RAID10 on SATA3 SSDs)
5. 2 JDBC sink connectors to ingest data, one to Postgres and one to Clickhouse using this JDBC driver

### Other descriptions
With setup above, when we run Postgres ingest the CPU utilization across all 3 KC nodes is very light, about 5% (loadavg5 about 1.2 on each kafkaconnect server). When we stop Postgres ingest and start Clickhouse ingest CPU utilization goes to 100% across all 3 nodes (loadavg5 about 18-20 on each kafkaconnect server).

There seems to be some code that causes very high CPU utilization when using this driver which exceeds any load expectations. As compared to Postgresql JDBC driver this one uses about 15-20 times more CPU resources.

**Comment by pan3793** [comment]
It's expected. See https://altinity.com/blog/clickhouse-and-python-getting-to-know-the-clickhouse-driver-client

**Comment by akamensky** [comment]
That article has no mention of JDBC driver nor of CPU utilization.

Do you mean that this is due to specifics of wire protocol?

**Comment by pan3793** [comment]
The matter thing is native TCP/IP protocol.

**Comment by akamensky** [comment]
We will try to profile JDBC driver on our end, and see whether any optimizations can be done. This x15-x20 times CPU utilization increase from JDBC driver would be a blocker for us (even if Clickhouse itself looks fine).

**Comment by pan3793** [comment]
The official HTTP-based JDBC driver should have a lower CPU cost than the native JDBC driver.

**Comment by akamensky** [comment]
We have run CPU profiling on this driver. It looks like for every insert the driver will call `ByteBuffer.allocate`. It spends about 70% of time doing memory allocations. Reusing buffers instead of allocating new buffer every time should be the way to go here. Also I think using `ByteBuffer.allocateDirect` AND re-using buffers would be even better performance improvement here.

![flame_cpu_local](https://user-images.githubusercontent.com/985805/122543378-4e0e5f00-d05e-11eb-88bd-d6237f6b1549.png)

**Comment by sundy-li** [comment]
@akamensky 
Hello, thanks for the profile results. 

It shows that resuing buffers can increase performance. 
We have considered it before, but I don't know whether we should do that or not.

1. JDBC clients are frequently used for single threads and never consider the multi-threads processing.
2. Pool the memory manually  OR  leave it to JVM?

If you can create a pr that proves its performance improvement in benchmarks, I think it will be reasonable to merge that.

**Comment by akamensky** [comment]
We have implemented buffer re-using internally and with it CPU utilization is less than half of the original driver.

Another improvement we did is to set `-XX:G1HeapRegionSize=8M`, that also reduced GC collection times with this driver.

With both of these changes the CPU utilization by this driver is still a bit high, but manageable.

**Comment by pan3793** [comment]
Amazing work! Are you interested to send a PR?

**Comment by akamensky** [comment]
@pan3793 our implementation is very basic and may be not the best, I think it would be better (and probably more efficient) if people more familiar with the driver actually implement this.

**Comment by pan3793** [comment]
You are too humble, you have already done better than me :)

**Comment by akamensky** [comment]
@pan3793 we prepared a crude implementation of re-using buffers that lowered CPU utilization significantly in our case, please take a look at linked PR.

FYI, I am no Java expert, this PR was prepared by a colleague who is an expert in Java. So I can't really provide fixes but feel free to review and modify as you see fit.
