### ISSUE TITLE
Connection is currently waiting for an insert operation, check your previous InsertStatement.

### ISSUE THREAD

**Issue by luoqingming110** [housepower/ClickHouse-Native-JDBC#357]
### Environment

- OS version: 
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs
![image](https://user-images.githubusercontent.com/7380805/127806299-6efd069f-7174-47a3-99fe-d3352a7fef16.png)

```
paste your error logs here

```

**Comment by pan3793** [comment]
DO NOT insert currently, it's the limitation of ClickHouse native protocol. A single thread with a large batch size can achieve high performance.
