### ISSUE TITLE
is there any way to set socket keep-alive?

### ISSUE THREAD

**Issue by comil4444** [housepower/ClickHouse-Native-JDBC#363]
- ClickHouse Native JDBC version:
        <dependency>
            <groupId>com.github.housepower</groupId>
            <artifactId>clickhouse-native-jdbc</artifactId>
            <version>2.1-stable</version>
        </dependency>

I use this driver to read data from ck, but always disconneted after a few sec. I check the source code and find no way the set socket keep alive option from the client side Orz. Could you plz help~

**Comment by xkommando** [comment]
there is a config:
```
        var props = new Properties(20);
        props.put(SettingKey.tcp_keep_alive, true);
...
        connection = driver.connect("*", props);
```
however i haven't tested myself.
