### ISSUE TITLE
Connection State Error

### ISSUE THREAD

**Issue by xkommando** [housepower/ClickHouse-Native-JDBC#364]
### Environment

- OS version: Ubuntu
- JDK version: 16
- ClickHouse Server version: 21.4.3.21
- ClickHouse Native JDBC version: 2.5.6
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
java.sql.SQLException: Connection is currently waiting for an insert operation, check your previous InsertStatement.
	at com.github.housepower.jdbc.misc.Validate.isTrue(Validate.java:41)
	at com.github.housepower.jdbc.ClickHouseConnection.getSampleBlock(ClickHouseConnection.java:263)
	at com.github.housepower.jdbc.statement.ClickHouseStatement.getSampleBlock(ClickHouseStatement.java:242)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.initBlockIfPossible(ClickHousePreparedInsertStatement.java:155)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.<init>(ClickHousePreparedInsertStatement.java:63)
	at com.github.housepower.jdbc.ClickHouseConnection.prepareStatement(ClickHouseConnection.java:160)
```

### Steps to reproduce
1. create the first prepared insert statement, and then no nothing, do not close stmt or conn, do not insert
2. create the second prepared insert statement

### cause
the `state` is stored at the connection object rather than in the statement object, and calling `connection.prepareStatement(sql)` actually sends the sql to the ck server and flip the `state` of the connection to `WAITING_INSERT`, the following call `connection.prepareStatement(sql)`  creates an illegal state error.

A typical scenario:
```
1. there are N tables to be inserted
2. creates N prepared insertion statement, each prepared stmt inserts to one table, cache the prepared stmts.
3. when the data comes, use the corresponding prepared statements to insert the data into different tables
```

In this case, one connection needs to be able to create many prepared stmts first, and then send the insertion block data later. sending sql and sending column data need to happen at `executeBatch`. 

I'm also open to other suggestoins, thanks!

**Comment by xkommando** [comment]
i fixed the issue by lazily create the prepare the statement.
thanks!

**Comment by meowl** [comment]
@xkommando I have the same issue for "lazily create the prepare the statement".
And I tried the last version, still has the same issue. 
I am looking forwad to the new release. Thanks.

> i fixed the issue by lazily create the prepare the statement.
> thanks!
