### ISSUE TITLE
 when to support ARRAY 

### ISSUE THREAD

**Issue by guoruyi-aa** [housepower/ClickHouse-Native-JDBC#366]
### Environment

- OS version: 
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
paste your error logs here
```

**Comment by sundy-li** [comment]
Already support, see https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java#L29

**Comment by guoruyi-aa** [comment]
Thank you ,I have tried,but it make mistakes&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "housepower/ClickHouse-Native-JDBC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月24日(星期二) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [housepower/ClickHouse-Native-JDBC]  when to support ARRAY  (#366)





 
Already support, see https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java#L29
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guoruyi-aa** [comment]
> Already support, see https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/clickhouse-native-jdbc/src/test/java/com/github/housepower/jdbc/InsertComplexTypeITest.java#L29

Thank you ,I have tried,but it make mistakes
 
java.sql.SQLException:Unsupported type ARRAY
