### ISSUE TITLE
Invalid argument: Missing port number

### ISSUE THREAD

**Issue by jiangjiguang** [housepower/ClickHouse-Native-JDBC#372]
clickhouse version is 21.5.9.4
 <clickhouse-native-jdbc.version>2.5.3</clickhouse-native-jdbc.version>
<clickhouse-jdbc.version>0.2.4</clickhouse-jdbc.version>

when one thread write data to clickhouse, it succeed.
But when two thread write data to clickhouse, there is the error:
com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Invalid argument: Missing port number. Stack trace:

Poco::Net::SocketAddress::init(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator > const&) @ 0x125189b7 in /usr/bin/clickhouse
DB::ClientInfo::read(DB::ReadBuffer&, unsigned long) @ 0xefa1bc0 in /usr/bin/clickhouse
DB::TCPHandler::receiveQuery() @ 0xfea0f0b in /usr/bin/clickhouse
DB::TCPHandler::receivePacket() @ 0xfe98267 in /usr/bin/clickhouse
DB::TCPHandler::runImpl() @ 0xfe90b0a in /usr/bin/clickhouse
DB::TCPHandler::run() @ 0xfea3bb9 in /usr/bin/clickhouse
Poco::Net::TCPServerConnection::start() @ 0x12522d2f in /usr/bin/clickhouse
Poco::Net::TCPServerDispatcher::run() @ 0x125247ba in /usr/bin/clickhouse
Poco::PooledThread::run() @ 0x1265d8d9 in /usr/bin/clickhouse
Poco::ThreadImpl::runnableEntry(void*) @ 0x126598ca in /usr/bin/clickhouse
start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
__clone @ 0x12171f in /lib/x86_64-linux-gnu/libc-2.27.so

**Comment by sundy-li** [comment]
Checkout that your jdbc URL contains port.

**Comment by jiangjiguang** [comment]
URL contains port，
the code is same,
when one thread write data to clickhouse, it succeed.
But when two thread write data to clickhouse, there is the error

**Comment by sundy-li** [comment]
You may need two connections if you have 2 threads write on parallel.

**Comment by andy1xx8** [comment]
@jiangjiguang using a DataSource with built-in Connection Pool might eliminate these kinda mistakes like HikariCP
