### ISSUE TITLE
Cannot return the affected rows count after updating

### ISSUE THREAD

**Issue by MephistoLynn** [housepower/ClickHouse-Native-JDBC#374]
### Environment

My Environment :
DBMS: ClickHouse (ver. 20.10.54441)
Case sensitivity: plain=exact, delimited=exact
Driver: com.github.housepower.clickhouse.native.jdbc (ver. 54380, JDBC1.1)
Effective version: ClickHouse (ver. 20.10.7.4)

Using this Driver ,in any updating operation ,I cannot see the message of affected rows count.

Is that the Driver's Setting or the function which not yet implemented ？

**Comment by sundy-li** [comment]
Is https://github.com/housepower/ClickHouse-Native-JDBC/blob/21cbb5ebab0a5cab54174e049c268ab8bc6da032/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/statement/ClickHouseStatement.java#L105  you want?

**Comment by MephistoLynn** [comment]
I think this is the reason of the problem

![image](https://user-images.githubusercontent.com/22832393/135039781-66dd7def-9e18-4a51-b742-14e340c83aba.png)

**Comment by sundy-li** [comment]
So Your SQL is not kind of insert SQL?

What's your update SQL?

**Comment by MephistoLynn** [comment]
That is my SQL for updata
`ALTER TABLE data_page_product_info UPDATE product_id=200 WHERE data_page_id=999;`

**Comment by sundy-li** [comment]
> That is my SQL for updata
> `ALTER TABLE data_page_product_info UPDATE product_id=200 WHERE data_page_id=999;`

You should know that clickhouse's alter update is async update, you never know when it is finished.

See: https://clickhouse.com/docs/en/sql-reference/statements/alter/update/
