### ISSUE TITLE
The build JDK version of release jar for clickhouse-native-jdbc 2.6.3 is 16.0.2，which is incompatible with Java 8/11

### ISSUE THREAD

**Issue by wallace-clickhouse** [housepower/ClickHouse-Native-JDBC#393]
### Environment

- OS version: suse 12.5
- JDK version:1.8
- ClickHouse Server version: 20.3.2.1
- ClickHouse Native JDBC version:2.6.3

the content of MANIFEST.MF is as follow:
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.8.4
Built-By: sundy
Build-Jdk: **16.0.2**

Under the JDK 1.8 runtime environment, error is reported when the insert operation is performed when I tested.
So is it a bug?Can you republish a 2.6.3 version of the jar compiled with JDK 1.8?

**Comment by pan3793** [comment]
OK, I will publish 2.6.4 in few minutes

**Comment by sundy-li** [comment]
Oh, my bad, I just got a new mac M1 and upgrade the jdk.

**Comment by wallace-clickhouse** [comment]
@pan3793 
Can you use the recompiled version and release it as 2.6.3?
Thank you！

**Comment by pan3793** [comment]
We can not redeploy a version which already exists in maven central.
The fixed version v2.6.4 has been sent to maven central, should be available soon.
(Maven Central may need much time to process it due to the log4shell issues)
