### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException is thrown for ResultSetMetaData.getColumnTypeName() method

### ISSUE THREAD

**Issue by gothug** [housepower/ClickHouse-Native-JDBC#40]
`val stmt = con.createStatement()`
`val rs = stmt.executeQuery("select 1")`
`val meta = rs.getMetaData`
`meta.getColumnTypeName(1))`

**Comment by sundy-li** [comment]
Hi, could u tell us which version are you using? I can not reproduce it with the latest code, a stable version will be soon

**Comment by gothug** [comment]
Hey, I'm using latest version 1.1-testing.

Thanks.

**Comment by sundy-li** [comment]
Confirmed #41
