### ISSUE TITLE
mybatis执行报 SQLFeatureNotSupportedException

### ISSUE THREAD

**Issue by Switcherman** [housepower/ClickHouse-Native-JDBC#404]
原因是解析时会调用 com.github.housepower.jdbc.wrapper.SQLResultSet 的 getType() 方法
默认实现是`throw new SQLFeatureNotSupportedException();`
且实现类没有重写.

这样设计的原因是什么?

**Comment by sundy-li** [comment]
https://github.com/housepower/ClickHouse-Native-JDBC/blob/21cbb5ebab/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java
 
 这个是实现类， 不知道为什么mybatis 路由到了  SQLResultSet 这个空接口

**Comment by Tiakon** [comment]
@dmitrybugakov  ，嗨，这个问题看似并没有解决，请问为什么要关闭这个议题？
