### ISSUE TITLE
Socket timeout or query timeout setting parameter

### ISSUE THREAD

**Issue by akhalifeh79** [housepower/ClickHouse-Native-JDBC#407]
I need to set a timeout for query processing( execution + reading data) time, I tried the parameters "query_timeout" and "connect_timeout" with no success. Any solution for this please?

 This is my test code:
@test
void testDriverTimeout(){
Properties clickhouseProperties = new Properties();
clickhouseProperties.setProperty("user", "**");
clickhouseProperties.setProperty("password", "**");
clickhouseProperties.setProperty("query_timeout", "1");// one second
clickhouseProperties.setProperty("connect_timeout", "3"); // 3 second

	DataSource balancedCkDs = new BalancedClickhouseDataSource("**", clickhouseProperties);
	List<String> result = new ArrayList<>();

	try (Connection conn1 = balancedCkDs.getConnection()) {
		PreparedStatement ps = conn1.prepareStatement("blab blab);
		long start1 = System.currentTimeMillis();
		ResultSet rs = ps.executeQuery();
		long end1 = System.currentTimeMillis();
		System.out.println("Elapsed Time in seconds: "+ (end1-start1)/1000);

		start1 = System.currentTimeMillis();
		while(rs.next()){
			result.add(rs.getString("external_id"));
		}
		end1 = System.currentTimeMillis();
		System.out.println("Elapsed Time for reading data in seconds: "+ (end1-start1)/1000);
	}catch (Exception ex){
		System.out.println(ex);
	}

	System.out.println(result);

}
Output:
Elapsed Time for query execution in seconds: 0
Elapsed Time for reading data in seconds: 73

No timeout exception thrown!

**Comment by sundy-li** [comment]
You should use `max_execution_time`

**Comment by akhalifeh79** [comment]
System is logging this:
09:23:13.880 [main] WARN com.github.housepower.jdbc.ClickhouseJdbcUrlParser - ignore undefined setting: max_execution_time=3

Indeed the class SettingKey does not contain this parameter. I'm using the version 2.6.4 which is the last.

**Comment by akhalifeh79** [comment]
<dependency>
            <groupId>com.github.housepower</groupId>
            <artifactId>clickhouse-native-jdbc-shaded</artifactId>
            <version>2.6.4</version>
        </dependency>

**Comment by akhalifeh79** [comment]
Hi,
adding the parameter "max_execution_time" as a custom SettingKey is causing a DB error as follows:
com.github.housepower.exception.ClickHouseSQLException: Software caused connection abort: socket write error
[].
Thanks for support

**Comment by sundy-li** [comment]
How about using:

```
 SettingKey key = SettingKey.builder()
            .withName("max_execution_time")
            .withType(SettingType.Int64)
            .build();

        Properties props = new Properties();
        ClickHouseConfig config = ClickHouseConfig.Builder.builder()
            .withProperties(props)
            .withSetting(key, 1)
            .withJdbcUrl(String.format(Locale.ROOT, "tcp:clickhouse://%s:%s", CK_HOST, CK_PORT))
            .build();

        String jdbcUrl = config.jdbcUrl();
```

**Comment by akhalifeh79** [comment]
Now it's working
Last error thrown by the system was relative to this line 
.withType(SettingType.Int64), I wrote SettingType.UTF8 instead of SettingType.Int64. My new code is like this:

SettingKey userDefined = SettingKey.builder()
				.withName("max_execution_time")
				.withType(SettingType.Int64)
				.build();
		Map<SettingKey, Serializable> settings = new HashMap<>();
		settings.put(SettingKey.user,"*");
		settings.put(SettingKey.password,"*");
		settings.put(userDefined,10L);


		DataSource balancedCkDs = new BalancedClickhouseDataSource(*", settings);

Thank you.
