### ISSUE TITLE
Will executeBatch support insert setting?

### ISSUE THREAD

**Issue by TheXs** [housepower/ClickHouse-Native-JDBC#414]
Hi, there.
Will insert setting like "insert_deduplication_token", "final" being support in batch insertion at future version? 
Best regards.

**Comment by sundy-li** [comment]
You can use custom setting key:

```
 SettingKey key = SettingKey.builder()
            .withName("max_execution_time")
            .withType(SettingType.Int64)
            .build();

        Properties props = new Properties();
        ClickHouseConfig config = ClickHouseConfig.Builder.builder()
            .withProperties(props)
            .withSetting(key, 1)
            .withJdbcUrl(String.format(Locale.ROOT, "tcp:clickhouse://%s:%s", CK_HOST, CK_PORT))
            .build();

        String jdbcUrl = config.jdbcUrl();
```

**Comment by TheXs** [comment]
> You can use custom setting key:
> 
> ```
>  SettingKey key = SettingKey.builder()
>             .withName("insert_deduplication_token")
>             .withType(SettingType.String)
>             .build();
> 
>         Properties props = new Properties();
>         ClickHouseConfig config = ClickHouseConfig.Builder.builder()
>             .withProperties(props)
>             .withSetting(key, "xxx")
>             .withJdbcUrl(String.format(Locale.ROOT, "tcp:clickhouse://%s:%s", CK_HOST, CK_PORT))
>             .build();
> 
>         String jdbcUrl = config.jdbcUrl();
> ```

Thx for reply.
The above is so far so good for config setting. However , I am talking about the sql-embedded sql, eg:
`insert into xx value('uuid', 'some value') settings insert_deduplication_token = 'uuid';`
Will these kinds of setting being support in BlockSettings or in other form of setting?

**Comment by sundy-li** [comment]
No，I don't  think we will support it. Because Setting Key is enough for now.
