### ISSUE TITLE
Date type is wrong when insert into clickhouse

### ISSUE THREAD

**Issue by sdlcwangsong** [housepower/ClickHouse-Native-JDBC#44]
when I insert into clickhouse table , I met a problem：
code：

`
Statement stmt = connection.createStatement();
        stmt.executeQuery("drop table if exists test_jdbc_example");
        stmt.executeQuery("create table test_jdbc_example(day Date, name String, age UInt8) Engine=Log");

        PreparedStatement pstmt = connection.prepareStatement("INSERT INTO test_jdbc_example VALUES(?, ?, ?)");

        for (int i = 0; i < 10; i++) {
            long time = 1530374400;
            System.out.println(new Date((time) * 1000));
            pstmt.setDate(1, new Date(time*1000));
            pstmt.setString(2, "Zhang San" + i);
            pstmt.setByte(3, (byte)i);
            pstmt.addBatch();
        }
        pstmt.executeBatch();
`

1530374400 convert to Date is ‘2018-07-01’， but in clickhouse Table，it show ‘2018-06-30’，I use it the wrong way？thank you.

SELECT *
FROM test_jdbc_example

┌────────day─┬─name───────┬─age─┐
│ 2018-06-30 │ Zhang San0 │   0 │
│ 2018-06-30 │ Zhang San1 │   1 │
│ 2018-06-30 │ Zhang San2 │   2 │

**Comment by zhang2014** [comment]
fixed in 1.3-stable
