### ISSUE TITLE
server 1.1.54289  jdbc  1.3  insert  data 

### ISSUE THREAD

**Issue by lingya** [housepower/ClickHouse-Native-JDBC#50]
Exception in thread "main" com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Unknown compression method: 226. Stack trace:

0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x2fe5936]
1. clickhouse-server(DB::Exception::Exception(std::string const&, int)+0x1f) [0x1293c2f]
2. clickhouse-server(DB::CompressedReadBufferBase::readCompressedData(unsigned long&, unsigned long&)+0x7ca) [0x3003cea]
3. clickhouse-server(DB::CompressedReadBuffer::nextImpl()+0x24) [0x3002f54]
4. clickhouse-server() [0x2963ff0]
5. clickhouse-server(DB::NativeBlockInputStream::readData(DB::IDataType const&, DB::IColumn&, DB::ReadBuffer&, unsigned long, double)+0x125) [0x29287d5]
6. clickhouse-server(DB::NativeBlockInputStream::readImpl()+0x7b6) [0x2929276]
7. clickhouse-server(DB::IProfilingBlockInputStream::read()+0x1e6) [0x2925116]
8. clickhouse-server(DB::TCPHandler::receiveData()+0x58) [0x129fc78]
9. clickhouse-server(DB::TCPHandler::receivePacket()+0x1b5) [0x12a0335]
10. clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x142) [0x12a06a2]
11. clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x241) [0x12a1311]
12. clickhouse-server(DB::TCPHandler::runImpl()+0x647) [0x12a1ab7]
13. clickhouse-server(DB::TCPHandler::run()+0x1c) [0x12a263c]
14. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x384ddef]
15. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x10b) [0x384f5fb]
16. clickhouse-server(Poco::PooledThread::run()+0x87) [0x39559b7]
17. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x3950546]
18. /lib64/libpthread.so.0(+0x7dc5) [0x7f2889116dc5]
19. /lib64/libc.so.6(clone+0x6d) [0x7f2886bf373d]

	at com.github.housepower.jdbc.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:32)
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:38)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:86)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveEndOfStream(PhysicalConnection.java:78)
	at com.github.housepower.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:132)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:61)
	at lyd.ai.ck.NativeC2CK.generateRowsList(NativeC2CK.java:59)
	at lyd.ai.ck.NativeC2CK.main(NativeC2CK.java:68)

**Comment by sundy-li** [comment]
Could u please show us the code? So we can reproduce and look into this problem

**Comment by lingya** [comment]
ok, 

create table ：

CREATE TABLE all_test(
    url String,
    host String,
    topDomain String,
    ipaddr String,
    country String,
    province String,
    area String,
    ispID String,
    audioVideoType UInt8,
    euAccessDate Date,
    euAccessTime UInt64
)
ENGINE = MergeTree(euAccessDate, (host,topDomain,audioVideoType), 8192);


java code : 

public class NativeC2CK {

	public static void nativeInsert() throws IOException, InterruptedException, SQLException, ClassNotFoundException {
		
		Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
	    Connection connection = DriverManager.getConnection("jdbc:clickhouse://localhost:9000","default","lyd.ai");

	    Statement stmt = connection.createStatement();
//	    stmt.executeQuery("drop table if exists test_jdbc_example");
//	    stmt.executeQuery("create table test_jdbc_example(day Date, name String, age UInt8) Engine=Log");

	    PreparedStatement pstmt = connection.prepareStatement("INSERT INTO  all_test VALUES    (?, ?, ?,?,?,?,?,?,?,?,?)");
        System.err.println("lll");
        
	    for (int i = 0; i < 10; i++) {
	    	
	    	pstmt.setString(1, "www.baidu.com/tt/t.q");
	    	pstmt.setString(2, "www.baidu.com");
	    	pstmt.setString(3, "baidu.com");
	    	pstmt.setString(4, "127.0.0.1");
	    	pstmt.setString(5, "中国");
	    	pstmt.setString(6, "北京");
	    	pstmt.setString(7, "北京");
	    	pstmt.setString(8, "电信");
	    	pstmt.setByte(9, (byte)0);
	    	pstmt.setDate(10, java.sql.Date.valueOf("2005-12-12"));
	    	pstmt.setLong(11, 2018080912);
	    	
//	        pstmt.setDate(1, new Date(System.currentTimeMillis()));
//	        pstmt.setString(2, "Zhang San" + i);
//	        pstmt.setByte(3, (byte)i);
	        pstmt.addBatch();
	        System.err.println(i);
	    }
	    pstmt.executeBatch();
//	    stmt.executeQuery("drop table if exists test_jdbc_example");
	    System.err.println("ll3333l");
//	    stmt.executeQuery("drop table test_jdbc_example");
	    
	    connection.close();
	}
	
	public static void main(String[] args) throws ClassNotFoundException, IOException, InterruptedException, SQLException {
		nativeInsert();
	}
}

**Comment by lingya** [comment]
ok ,

create table:
CREATE TABLE  all_test(
    url String,
    host String,
    topDomain String,
    ipaddr String,
    country String,
    province String,
    area String,
    ispID String,
    audioVideoType UInt8,
    euAccessDate Date,
    euAccessTime UInt64
)
ENGINE = MergeTree(euAccessDate, (host,topDomain,audioVideoType), 8192);



java  code : 

Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
	    Connection connection = DriverManager.getConnection("jdbc:clickhouse://localhost:9000","default","lyd.ai");
	    Statement stmt = connection.createStatement();
	    PreparedStatement pstmt = connection.prepareStatement("INSERT INTO  all_test VALUES(?, ?, ?,?,?,?,?,?,?,?,?)");
       
	    for (int i = 0; i < 10; i++) {
	    	
	    	pstmt.setString(1, "www.baidu.com/tt/t.q");
	    	pstmt.setString(2, "www.baidu.com");
	    	pstmt.setString(3, "baidu.com");
	    	pstmt.setString(4, "127.0.0.1");
	    	pstmt.setString(5, "中国");
	    	pstmt.setString(6, "北京");
	    	pstmt.setString(7, "北京");
	    	pstmt.setString(8, "电信");
	    	pstmt.setByte(9, (byte)0);
	    	pstmt.setDate(10, java.sql.Date.valueOf("2005-12-12"));
	    	pstmt.setLong(11, 2018080912);
	  
	        pstmt.addBatch();
	   
	    }
	    pstmt.executeBatch();

**Comment by sundy-li** [comment]
Thanks for your feedback. We mistake the Chinese String size , fixed

**Comment by lingya** [comment]
Is it the latest in maven repository  ？

**Comment by sundy-li** [comment]
yes，it's releasing...

**Comment by sundy-li** [comment]
V1.4-stable is on the maven central.

https://mvnrepository.com/artifact/com.github.housepower/clickhouse-native-jdbc/1.4-stable
