### ISSUE TITLE
Port 9000 is for clickhouse-client program

### ISSUE THREAD

**Issue by wzp06354** [housepower/ClickHouse-Native-JDBC#51]
I user ClickHouse-Native-JDBC to send data into clickhouse,but get expection like this:
 java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 172.18.164.98, port: 9000; Port 9000 is for clickhouse-client program.
You must use port 8123 for HTTP.

I don't know that i should add Clickhouse-Jdbc dependency into pom.xml or not .But when i don't add  Clickhouse-Jdbc dependency,there is a exception that is No suitable driver found for jdbc url.

The version of clickhouse is 18.1.0

**Comment by zhang2014** [comment]
Remove ClickHouse-Native-JDBC or yandex/clickhouse-jdbc from the classpath, because they use the same jdbc url

**Comment by wzp06354** [comment]
When i delete `ru.yandex.clickhouse` dependencies from pom.xml and rerun it ,i get a Expection:
`No suitable driver found for jdbc:clickhouse://xx.xx.xx.xx:9000`
