### ISSUE TITLE
How to set the database in the JDBC connection url.

### ISSUE THREAD

**Issue by ggservice007** [housepower/ClickHouse-Native-JDBC#53]
```java
Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
Connection connection = 
       DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9001/test");
```

Error, Can not the database named test.

**Comment by zhang2014** [comment]
The reason maybe that you don't have the `test` database.
In this case, `test` database is only used as the default database in this connection.

**Comment by ggservice007** [comment]
Connection connection = 
       DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:9001/happy_test_db");

<img width="953" alt="a1" src="https://user-images.githubusercontent.com/9192908/44615917-cab16c80-a877-11e8-99f3-84cdc9bbb0a5.png">

Error is as follow.
```cmd
DB::ExceptionDB::Exception: Database /happy_test_db doesn't exist
```

@zhang2014  Thank you.

**Comment by zhang2014** [comment]
fixed in https://github.com/housepower/ClickHouse-Native-JDBC/commit/801bdcfc9617bc79fb6b59fb48d745969143a07a 

Please provide your ClickHose-Native-JDBC version

**Comment by ggservice007** [comment]
v1.4-stable

**Comment by ggservice007** [comment]
@zhang2014 Thanks you so much.

 Check again, I am not use v1.4-stable version.

Sorry, It is my fault.

After check to v1.4-stable, it works.

**Comment by zhang2014** [comment]
OK : )
