### ISSUE TITLE
How to access the MySQL directly?

### ISSUE THREAD

**Issue by ggservice007** [housepower/ClickHouse-Native-JDBC#54]
ClickHouse is pretty cool.

I want to use the SQL with ClickHouse-Native-JDBC to connect to the MySQL by using ClickHouse.

How to do?  Any idea about ClickHouse and MySQL.

Maybe is it slow for ClickHouse with ODBC?

I want to use JDBC directly with ClickHouse and MySQL.

**Comment by zhang2014** [comment]
I see your [issues](https://github.com/yandex/ClickHouse/issues/2951) , you can do according to the answer of @blinkov : )
