### ISSUE TITLE
Error "Unknown compression method: 108" when doing arrayMap() with tuple() over two distinctly-typed arrays.

### ISSUE THREAD

**Issue by gothug** [housepower/ClickHouse-Native-JDBC#58]
Reproduced on the version 1.5-stable with:

Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
Connection connection = DriverManager.getConnection("jdbc:clickhouse://localhost:9000","default","");
Statement stmt = connection.createStatement();
val rs = stmt.executeQuery("select distinct arrayMap((x,y) -> tuple(x,y), nums, names) from (select arrayJoin([1,2]) as id, id = 1 ? [1,2,3] : [10,20,30] as nums, id = 1 ? ['one', 'two', 'three'] : ['a','b','c'] as names)")

**Comment by gothug** [comment]
Rewritten the query to look a bit simpler:

`val rs = stmt.executeQuery("select distinct arrayMap((x,y) -> tuple(x,y), nums, names) from (SELECT [[1],[10]] AS nums, [['one'],['a']] AS names) ARRAY JOIN nums, names")`

**Comment by hexintao** [comment]
have you solved? I met that problem too..

**Comment by sundy-li** [comment]
I can reproduce this bug, still working on how to resolve it.
