### ISSUE TITLE
Cannot use syntax for insert with multiple values via jdbc driver, an error occurs

### ISSUE THREAD

**Issue by gothug** [housepower/ClickHouse-Native-JDBC#59]
Version 1.5-stable, a way to reproduce:

Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
Connection connection = DriverManager.getConnection("jdbc:clickhouse://localhost:9000","default","");
Statement stmt = connection.createStatement();
stmt.execute("CREATE TEMPORARY TABLE tmp_debug_jdbc(id Int32) ENGINE = Memory")
stmt.execute("INSERT INTO tmp_debug_jdbc values (1), (2)")

**Comment by zhang2014** [comment]
👍 Thank you. I will fix this problem as soon as possible : )

BTW, Cause of the problem: ` (1), (2)` contains spaces. `ClickHouse-Native-JDBC` contains a simple SQL parser, which is clearly imperfect : (

**Comment by gothug** [comment]
Hm, this one also fails for me:

`stmt.execute("INSERT INTO tmp_debug_jdbc values(1),(2)")`

**Comment by gothug** [comment]
Thanks a lot!
