### ISSUE TITLE
ClickHouseResultSet.getObject() works incorrectly for Nullable data types.

### ISSUE THREAD

**Issue by sarg** [housepower/ClickHouse-Native-JDBC#61]
ResultSet incorrectly returns 0.0 instead of null for my Nullable(Float32) column. Looking into the sources I have found that `getObject()` returns default column value, which is taken from nested data type in case of Nullable. 

https://github.com/housepower/ClickHouse-Native-JDBC/blob/fa6b1d3b543da9bd9934948f45ff984e61c8bf31/src/main/java/com/github/housepower/jdbc/ClickHouseResultSet.java#L185

**Comment by gothug** [comment]
As some work-around I'm checking rs.wasNull() after calling rs.getDataType(columnNum) to check if the returned value is actually a _null_.

**Comment by sundy-li** [comment]
Yes, when you are using getXXX()  for nullable column, always call `rs.wasNull()` method to check.
