### ISSUE TITLE
No support for unsigned int values.

### ISSUE THREAD

**Issue by adubovikov** [housepower/ClickHouse-Native-JDBC#65]
Hi, unfortunately, the driver doesn't support UINT.

i.e. UINT16 - value 36199 will be return as  -29337. 

Looks like the getObject->Number makes  wrong byte shift  i.e. ("36199 - 65535 (max uin16))) and as result we got wrong value. IMHO the best way implement getUINT8/16/32 in the ResultSet, because the beauty of CH is unsigned numbers ;-)

**Comment by sundy-li** [comment]
Because java int16 ranges from ( -32768 ~ + 32767).

Would it be ok to use getLong method for UInt32 numbers ?

**Comment by adubovikov** [comment]
This is not correct, Java has support for signed numbers by default, but this is doesn't mean that you couldnt' get UINT and set the value to LONG value, also for your proposal: if you have a number that is bigger than INT32 and has been stored in UInt32 field, the result will be wrong. As I said, the best way implement byte shift in the Object convertion for UINT tables and in the ResultSet add getUint[8|16|32].
as another workaround, during CH query you can use toINT converter, but this is not the best way.

**Comment by sundy-li** [comment]
@adubovikov  Yes, u are right. We will try to add the UIntXX support

**Comment by sundy-li** [comment]
@adubovikov  Hi, could this pr  test help with you?
PR: #66 
Tests: https://github.com/housepower/ClickHouse-Native-JDBC/pull/66/files#diff-fdfe80ee0174a0567c28a321a6f1455cR222

**Comment by adubovikov** [comment]
sorry,  I am on vacation, will do once I be at my desktop. Thank you!

**Comment by adubovikov** [comment]
Hi,

I have tested! Works perfect! Thank you! I will close the ticket.
