### ISSUE TITLE
Add DatabaseMetadata Support

### ISSUE THREAD

**Issue by BlankRain** [housepower/ClickHouse-Native-JDBC#67]
SQLDatabaseMetadata

```
java.sql.SQLFeatureNotSupportedException
:at [com.github.housepower.jdbc.wrapper.SQLConnection getMetaData SQLConnection.java
```

**Comment by sundy-li** [comment]
Well, I saw this issue yesterday on https://github.com/metabase/metabase/issues/3332.

We are trying to add this support.

**Comment by BlankRain** [comment]
thank you..

**Comment by acmeguy** [comment]
Hi, has any progress been made on this?
The Yandex driver has a fairly good starting point of this but I have no experience relevant to contributing (even though I would love to help)

**Comment by sundy-li** [comment]
Me too, it's a little complicated to understand all the functions in `DatabaseMetaData ` interfaces.

Maybe someone could help to give a better pr of this issue?

**Comment by BlankRain** [comment]
@sundy-li   https://github.com/yandex/clickhouse-jdbc/blob/master/src/main/java/ru/yandex/clickhouse/ClickHouseDatabaseMetadata.java 
This source code may helps.
