### ISSUE TITLE
Performance and memory usage issues

### ISSUE THREAD

**Issue by gothug** [housepower/ClickHouse-Native-JDBC#70]
I tried to do some simple performance tests to compare clickhouse-native-jdbc and official clickhouse-jdbc drivers in terms of speed and memory usage. Below are two examples for making a simple select query from CH _numbers_ function.

**clickhouse-jdbc**:

    Register http driver..
    Executing sql: SELECT number as n1 from numbers(100000000)
      0% Total memory (MB):   960, used memory (MB):    20, time elapsed:    354(+   354 ms)
     10% Total memory (MB):  1211, used memory (MB):   386, time elapsed:   1425(+  1071 ms)
     20% Total memory (MB):  1676, used memory (MB):   777, time elapsed:   2433(+  1008 ms)
     30% Total memory (MB):  1595, used memory (MB):   674, time elapsed:   3313(+   880 ms)
     40% Total memory (MB):  1525, used memory (MB):   740, time elapsed:   4197(+   884 ms)
     50% Total memory (MB):  1430, used memory (MB):   140, time elapsed:   5038(+   841 ms)
     60% Total memory (MB):  1375, used memory (MB):   524, time elapsed:   5868(+   830 ms)
     70% Total memory (MB):  1301, used memory (MB):   358, time elapsed:   6698(+   830 ms)
     80% Total memory (MB):  1236, used memory (MB):   401, time elapsed:   7529(+   831 ms)
     90% Total memory (MB):  1164, used memory (MB):   121, time elapsed:   8358(+   829 ms)
    100% Total memory (MB):  1103, used memory (MB):   116, time elapsed:   9193(+   835 ms)
    4999999950000000

    real    0m9.652s
    user    0m9.728s
    sys     0m0.388s

**clickhouse-native-jdbc**:

    Register native driver..
    Executing sql: SELECT number as n1 from numbers(100000000)
      0% Total memory (MB):  9092, used memory (MB):  6802, time elapsed:  21052(+ 21052 ms)
     10% Total memory (MB): 12213, used memory (MB):  6598, time elapsed:  30561(+  9509 ms)
     20% Total memory (MB): 12282, used memory (MB):  6706, time elapsed:  30930(+   369 ms)
     30% Total memory (MB): 12390, used memory (MB):  6786, time elapsed:  31252(+   322 ms)
     40% Total memory (MB): 12412, used memory (MB):  6757, time elapsed:  31576(+   324 ms)
     50% Total memory (MB): 12510, used memory (MB):  6713, time elapsed:  31897(+   321 ms)
     60% Total memory (MB): 12523, used memory (MB):  6585, time elapsed:  32222(+   325 ms)
     70% Total memory (MB): 12523, used memory (MB):  8020, time elapsed:  32521(+   299 ms)
     80% Total memory (MB): 12608, used memory (MB):  7876, time elapsed:  32836(+   315 ms)
     90% Total memory (MB): 12619, used memory (MB):  7639, time elapsed:  33166(+   330 ms)
    100% Total memory (MB): 12530, used memory (MB):  7413, time elapsed:  33472(+   306 ms)
    4999999950000000

    real    0m33.958s
    user    3m8.092s
    sys     0m3.816s

The first lines in the above examples (marked as 0%) mark the moment when the driver has returned a ResultSet object for the sql (`ResultSet ClickHouseStatement.executeQuery(String query)`) and it is ready to be iterated.

In these particular examples it can be seen that the official http jdbc driver returns the result set almost instantly (~300ms). Next lines with increasing percentages show the processing of the result set by iterating it via `boolean ClickHouseResultSet.next()` and `long ClickHouseResultSet.getLong(int columnIndex)`.

For clickhouse-native-jdbc driver there is a considerable delay before the ResultSet object is ready (also, what is not seen here, since these tests are only for one particular result size, but this delay grows as the amount of rows returned by the query increases). By the time the ResultSet is ready a significant amount of memory is used (particularly in comparison to the http driver).

Overall, on this particular example the clickhouse-native-jdbc driver is 3 times slower in total and uses an order of magnitude more memory.

I tried to dig into sources and found that while preparing the result set in `ClickHouseStatement.executeUpdate(String query)` the QueryResponse object is being built by receiving all responses from `PhysicalConnection.receiveResponse(..)` and storing the results in `ArrayList<RequestOrResponse>`. So it looks like all the data is being read from the DB in advance prior to returning the ResultSet object which takes time and memory. As a result I wonder why it is implemented like this. Maybe I'm missing something or I do not understand some details or maybe it was just not a priority to make the driver memory-efficient for large data sets and it is planned to be improved upon in the future.

Would be grateful for any comments and clarifications.

**Comment by zhang2014** [comment]
@gothug This is just for simpler implementation. This problem will be fixed by #73

**Comment by gothug** [comment]
@Lauri-Nomme I did not commit these tests cleanly anywhere.

Please see the code for these tests here:
https://gist.github.com/gothug/9de3fc1fa6a3a9e7b71c22ab0a3c7a0c
https://gist.github.com/gothug/3b35fe0cec302efe6f8314a9cab8865e

**Comment by sundy-li** [comment]
Now the performance improves a lot. See https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/Benchmark.md.
