### ISSUE TITLE
Support SQLStatement FetchSize Injection

### ISSUE THREAD

**Issue by shanling2004** [housepower/ClickHouse-Native-JDBC#76]
Can we support SQLStatement FetchSize Injection?

https://github.com/housepower/ClickHouse-Native-JDBC/blob/7ece148dc6dd332d3d662fd5fcb14925ecc95591/src/main/java/com/github/housepower/jdbc/wrapper/SQLStatement.java#L113-L115
```
  @Override
    public void setFetchSize(int rows) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

```

**Comment by pan3793** [comment]
Override in `ClickHouseStatement` with empty body, suppressed `SQLFeatureNotSupportedException`, but no actual effect.
```
    @Override
    public void setFetchSize(int rows) throws SQLException {
    }
```
