### ISSUE TITLE
Freezing on Read

### ISSUE THREAD

**Issue by Slind14** [housepower/ClickHouse-Native-JDBC#77]
Hi there,
I'm unable to get this lib to work. It is always freezing for me. Do you have any idea why?

![image](https://user-images.githubusercontent.com/3914677/53866921-ffef0200-3ff2-11e9-8a84-de7af1e2d245.png)

**Comment by sundy-li** [comment]
What's the error log?

**Comment by Slind14** [comment]
no errors are being thrown, it freezes.

**Comment by Slind14** [comment]
Could it be because I have multiple jdbc drivers?

**Comment by Lauri-Nomme** [comment]
Looks like you're connecting to something that doesn't speak the correct
protocol.

**Comment by sundy-li** [comment]
@Slind14  could u show the connection urls and params ?

**Comment by Slind14** [comment]
A clean install of CH fixed it, thanks.
