### ISSUE TITLE
How to read arrays, tuples, etc.

### ISSUE THREAD

**Issue by anthonyshull** [housepower/ClickHouse-Native-JDBC#78]
Maybe this is what you mean by `Non-values format`, but how do I access array, tuple, etc. values? This makes me think that it just hasn't been implemented yet?

https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/src/main/java/com/github/housepower/jdbc/wrapper/SQLArray.java

**Comment by sundy-li** [comment]
Maybe [ this](https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/src/test/java/com/github/housepower/jdbc/QueryComplexTypeITest.java#L108) could help you.

**Comment by anthonyshull** [comment]
I am using Clojure and I get this error:

```
Unable to convert: class com.github.housepower.jdbc.ClickHouseArray to Object[]
```
