### ISSUE TITLE
FixedString with Nullable broken

### ISSUE THREAD

**Issue by Slind14** [housepower/ClickHouse-Native-JDBC#81]
When retrieving a string from the ResultSet which is a Nullable(FixedString(n)) Column it returns `????????????????????????????????????` (probably something different and just encoded to ?) instead of `null`.

![image](https://user-images.githubusercontent.com/3914677/53938952-10b27d00-40b2-11e9-9f99-03c7eded448d.png)

**Comment by sundy-li** [comment]
Fixed in #138 #133
