### ISSUE TITLE
Slow performance when batch inserting wide rows

### ISSUE THREAD

**Issue by hanguyen6** [housepower/ClickHouse-Native-JDBC#86]
### JDBC version in pom.xml
1.6-stable 

### ClickHouse version
19.4

### Steps to reproduce
- Inserting wide rows (175 columns, mostly numerical values) in batches of 100,000 records is giving performance 2-3 worse than using HTTP-JDBC driver.  Can anyone help me understand  the way Native-jdbc driver works in comparison with HTTP jdbc driver when inserting wide rows ?

**Comment by sundy-li** [comment]
Now, the wide column insert improves a lot, see https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/Benchmark.md.

**Comment by hanguyen6** [comment]
Thanks. I ended up using clickhouse-client to load data but I am excited to test new version.  Do you have its performance compared with clickhouse-client ?
