### ISSUE TITLE
batch insertion fail with "Unknown data type family" when contains an array column

### ISSUE THREAD

**Issue by jewelzhu** [housepower/ClickHouse-Native-JDBC#88]
### JDBC version in pom.xml
'com.github.housepower:clickhouse-native-jdbc:1.6-stable'

### ClickHouse version
ClickHouse server version 18.14.10 revision 54409.

### Error  logs
com.github.housepower.jdbc.ClickHouseSQLException: DB::ExceptionDB::Exception: Unknown data type family: duration. Stack trace:

0. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x9659a16]
1. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x355b95f]
2. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::DataTypeFactory::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<DB::IAST> const&, unsigned char) const+0xba2) [0x7015062]
3. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::DataTypeFactory::get(std::shared_ptr<DB::IAST> const&, unsigned char) const+0x118) [0x70152a8]
4. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::DataTypeFactory::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned char) const+0x90) [0x70154f0]
5. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::NativeBlockInputStream::readImpl()+0x60a) [0x6fe98da]
6. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x135) [0x6fdf6a5]
7. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::TCPHandler::receiveData()+0x75) [0x3565e95]
8. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::TCPHandler::receivePacket()+0x3d5) [0x35675d5]
9. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::TCPHandler::readData(DB::Settings const&)+0x193) [0x3567ce3]
10. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::TCPHandler::processInsertQuery(DB::Settings const&)+0x1f6) [0x3568136]
11. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x9f8) [0x3568c98]
12. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(DB::TCPHandler::run()+0x1c) [0x356921c]
13. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x978dddf]
14. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe5) [0x978e4d5]
15. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x9ba7581]
16. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x9ba3858]
17. /opt/tiger/ch_debian_bin/usr/bin/clickhouse-server() [0xa0e7e3f]
18. /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7f7567abd494]
19. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f7566e6facf]

	at com.github.housepower.jdbc.protocol.ExceptionResponse.readExceptionFrom(ExceptionResponse.java:32)
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:38)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:86)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveEndOfStream(PhysicalConnection.java:78)
	at com.github.housepower.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:138)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:61)
	at com.bytedance.webarch.log.storage.ClickhouseWriterTest.simplestReproduce(ClickhouseWriterTest.java:187)

### Steps to reproduce
MyTable:
CREATE TABLE trace.trace ( start_time DateTime,  from_service String,  from_method String,  to_service String,  to_method String,  host UInt32,  error UInt8,  caller_or_callee UInt8,  tags Array(String),  duration UInt64,  log_id String) ENGINE = MergeTree() PARTITION BY (toYYYYMMDD(start_time), toHour(start_time)) ORDER BY (start_time, to_service, to_method, host) SETTINGS index_granularity = 8192

JavaCode:
    public void simplestReproduce() throws Exception {
        List<Trace> data = Arrays.asList(
                new Trace(new Timestamp(1557155684L),
                        "fromService11111",
                        "fromMethod",
                        "toService",
                        "toMethod",
                        111,
                        0,
                        0,
                        Arrays.asList("tag=test"),
                        10,
                        "logIdtest"
                ),
                new Trace(new Timestamp(1557155684L),
                        "fromService11111",
                        "fromMethod",
                        "toService",
                        "toMethod",
                        111,
                        0,
                        0,
                        Arrays.asList("tag=test"),
                        10,
                        "logIdtest"
                ));
        String sql = "INSERT INTO trace(start_time, from_service, from_method, to_service, to_method, host, error, caller_or_callee, tags, duration, log_id) " +
                "VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        Class.forName("com.github.housepower.jdbc.ClickHouseDriver");
        Connection connection = DriverManager.getConnection("jdbc:clickhouse://10.8.147.45:9000/trace");
        PreparedStatement statement = connection.prepareStatement(sql);
        for (Trace trace : data) {
            int i = 1;
            statement.setTimestamp(i++, trace.getStartTime());
            statement.setString(i++, trace.getFromService());
            statement.setString(i++, trace.getFromMethod());
            statement.setString(i++, trace.getToService());
            statement.setString(i++, trace.getToMethod());
            statement.setInt(i++, trace.getHost());
            statement.setInt(i++, trace.getError());
            statement.setInt(i++, trace.getCallerOrCallee());
            statement.setArray(i++, connection.createArrayOf("text", trace.getTags().toArray()));
            statement.setLong(i++, trace.getDuration());
            statement.setString(i++, trace.getLogId());
            statement.addBatch();
        }
        statement.executeBatch();
    }

### Other descriptions
When the batch insert list has only one row, the insertion succeeds. When the array column in batch insertion is empty, the insertion also succeeds. But when batch inserts more then one rows, and the array column is not empty,  the server always returns "DB::ExceptionDB::Exception: Unknown data type family: xxx"

Thanks in advance.

**Comment by sundy-li** [comment]
Sorry for the delay, this bug is fixed in ac9391585ded977d803c61a04d0ee1c06443fdce.

**Comment by stLalo** [comment]
I can't see the new release in Maven.

**Comment by sundy-li** [comment]
It will be soon(in 24 hours).  and you can build the repo by using `mvn install` by you own.

**Comment by jewelzhu** [comment]
thanks, after upgrade to 'com.github.housepower:clickhouse-native-jdbc:1.7-stable' , this issue doesn't occur again

**Comment by FrolovIgor** [comment]
Hi! 

I have same problem, but my version is **'1.7-stable'**

**Logs**

19/10/01 15:26:57 WARN TaskSetManager: Lost task 61.0 in stage 2.0 (TID 184, hd206.vimpelcom.ru, executor 40): java.sql.SQLException: Unknown data type family:lable
	at com.github.housepower.jdbc.misc.Validate.isTrue(Validate.java:14)
	at com.github.housepower.jdbc.data.DataTypeFactory.get(DataTypeFactory.java:62)
	at com.github.housepower.jdbc.data.DataTypeFactory.get(DataTypeFactory.java:33)
	at com.github.housepower.jdbc.data.Block.readFrom(Block.java:85)
	at com.github.housepower.jdbc.protocol.DataResponse.readFrom(DataResponse.java:32)
	at com.github.housepower.jdbc.protocol.RequestOrResponse.readFrom(RequestOrResponse.java:36)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveResponse(PhysicalConnection.java:86)
	at com.github.housepower.jdbc.connect.PhysicalConnection.receiveSampleBlock(PhysicalConnection.java:64)
	at com.github.housepower.jdbc.ClickHouseConnection.sendInsertRequest(ClickHouseConnection.java:131)
	at com.github.housepower.jdbc.statement.ClickHousePreparedInsertStatement.executeBatch(ClickHousePreparedInsertStatement.java:61)
