### ISSUE TITLE
Requests hang when requesting through a proxy.

### ISSUE THREAD

**Issue by kas-kad** [housepower/ClickHouse-Native-JDBC#92]
### JDBC version in pom.xml
1.6, 1.7

### ClickHouse version
18.16.1

### Steps to reproduce
We have clickhouse balancing proxy. In our Spring boot app, datasource.url refers to that proxy. All the requests to the datasource just hang. Switching back to a particular node url fixes the issue. As well as switching to the official yandex jdbc client.

**Comment by Lauri-Nomme** [comment]
Does the balancing proxy expose the native binary protocol?

**Comment by pan3793** [comment]
Close because no enough information to reproduce, feel free to reopen it if you'd like to provide more information for investigating.
