### ISSUE TITLE
How ClickHouse-Native-JDBC connects multiple instances of cluster

### ISSUE THREAD

**Issue by johncai0** [housepower/ClickHouse-Native-JDBC#93]

**Comment by johncai0** [comment]
How ClickHouse-Native-JDBC connects multiple instances of cluster

**Comment by berace** [comment]
> How ClickHouse-Native-JDBC connects multiple instances of cluster

请问你的问题解决了吗

**Comment by pan3793** [comment]
This feature not support yet.
