### ISSUE TITLE
 write clickhouse with spark jdbc  ,number of records is error

### ISSUE THREAD

**Issue by yanchaoguo** [housepower/ClickHouse-Native-JDBC#94]
jdbc driver :com.github.housepower:clickhouse-native-jdbc:1.6-stable
spark version: 2.0
operator：df.limit(10000).write.mode("append").jdbc(ckUrl,ckTableN,pro)
error : number of records more than 10000  ,it is 210000

**Comment by tauitdnmd** [comment]
@yanchaoguo  what's the engine you are using? 
As i can see you are about to write append to the existing data

**Comment by pan3793** [comment]
@yanchaoguo Any update? If not, I will close issue in 3 days.
